pub type WORD8 = core::ffi::c_schar;
pub type UWORD8 = core::ffi::c_uchar;
pub type FLOAT32 = core::ffi::c_float;
#[no_mangle]
pub static mut ixheaacd_pvc_smoothing_wind_tab_ns4: [FLOAT32; 4] = [
    2.9233807677393114e-001f32,
    2.8099141963307617e-001f32,
    2.4582604080136389e-001f32,
    1.8084446279162875e-001f32,
];
#[no_mangle]
pub static mut ixheaacd_pvc_smoothing_wind_tab_ns16: [FLOAT32; 16] = [
    7.9120074720078801e-002f32,
    7.8929352455315405e-002f32,
    7.8356252741836802e-002f32,
    7.7397889626247995e-002f32,
    7.6049149540866515e-002f32,
    7.4302186813164264e-002f32,
    7.2145604983589517e-002f32,
    6.9563171210312247e-002f32,
    6.6531787206720316e-002f32,
    6.3018197524834882e-002f32,
    5.8973400826190611e-002f32,
    5.4322528277253423e-002f32,
    4.8944795582858927e-002f32,
    4.2628371779453236e-002f32,
    3.4946569619925177e-002f32,
    2.4770667091351901e-002f32,
];
#[no_mangle]
pub static mut ixheaacd_pvc_smoothing_wind_tab_ns3: [FLOAT32; 3] = [
    3.7911649807579761e-001f32,
    3.5280765527510910e-001f32,
    2.6807584664909323e-001f32,
];
#[no_mangle]
pub static mut ixheaacd_pvc_smoothing_wind_tab_ns12: [FLOAT32; 12] = [
    1.0440702692045410e-001f32,
    1.0395945931915132e-001f32,
    1.0261281883061703e-001f32,
    1.0035462721037963e-001f32,
    9.7161686576578310e-002f32,
    9.2995740369570576e-002f32,
    8.7795494664707929e-002f32,
    8.1461666975864891e-002f32,
    7.3826916738979523e-002f32,
    6.4587661325082549e-002f32,
    5.3116303570036522e-002f32,
    3.7720597498577493e-002f32,
];
#[no_mangle]
pub static mut ixheaacd_pred_coeff_pvc_id_boundaries_1: [UWORD8; 2] = [
    17 as core::ffi::c_int as UWORD8,
    68 as core::ffi::c_int as UWORD8,
];
#[no_mangle]
pub static mut ixheaacd_q_factor_table_mode_1: [FLOAT32; 4] = [
    (1.0f64 / 256.0f64) as FLOAT32,
    (1.0f64 / 256.0f64) as FLOAT32,
    (1.0f64 / 128.0f64) as FLOAT32,
    (1.0f64 / 2.0f64) as FLOAT32,
];
#[no_mangle]
pub static mut ixheaacd_pred_coeff_table_1_mode_1: [[[WORD8; 8]; 3]; 3] = [
    [
        [
            0x4f as core::ffi::c_int as WORD8,
            0x5b as core::ffi::c_int as WORD8,
            0x57 as core::ffi::c_int as WORD8,
            0x52 as core::ffi::c_int as WORD8,
            0x4d as core::ffi::c_int as WORD8,
            0x65 as core::ffi::c_int as WORD8,
            0x45 as core::ffi::c_int as WORD8,
            0x57 as core::ffi::c_int as WORD8,
        ],
        [
            0xf3 as core::ffi::c_int as WORD8,
            0xf as core::ffi::c_int as WORD8,
            0x18 as core::ffi::c_int as WORD8,
            0x20 as core::ffi::c_int as WORD8,
            0x19 as core::ffi::c_int as WORD8,
            0x4f as core::ffi::c_int as WORD8,
            0x3d as core::ffi::c_int as WORD8,
            0x23 as core::ffi::c_int as WORD8,
        ],
        [
            0x78 as core::ffi::c_int as WORD8,
            0x57 as core::ffi::c_int as WORD8,
            0x55 as core::ffi::c_int as WORD8,
            0x50 as core::ffi::c_int as WORD8,
            0x50 as core::ffi::c_int as WORD8,
            0x20 as core::ffi::c_int as WORD8,
            0x36 as core::ffi::c_int as WORD8,
            0x37 as core::ffi::c_int as WORD8,
        ],
    ],
    [
        [
            0x4c as core::ffi::c_int as WORD8,
            0x5f as core::ffi::c_int as WORD8,
            0x53 as core::ffi::c_int as WORD8,
            0x37 as core::ffi::c_int as WORD8,
            0x1e as core::ffi::c_int as WORD8,
            0xfd as core::ffi::c_int as WORD8,
            0x15 as core::ffi::c_int as WORD8,
            0xa as core::ffi::c_int as WORD8,
        ],
        [
            0x5 as core::ffi::c_int as WORD8,
            0xe as core::ffi::c_int as WORD8,
            0x28 as core::ffi::c_int as WORD8,
            0x41 as core::ffi::c_int as WORD8,
            0x48 as core::ffi::c_int as WORD8,
            0x6e as core::ffi::c_int as WORD8,
            0x54 as core::ffi::c_int as WORD8,
            0x5b as core::ffi::c_int as WORD8,
        ],
        [
            0x59 as core::ffi::c_int as WORD8,
            0x47 as core::ffi::c_int as WORD8,
            0x40 as core::ffi::c_int as WORD8,
            0x40 as core::ffi::c_int as WORD8,
            0x3d as core::ffi::c_int as WORD8,
            0x33 as core::ffi::c_int as WORD8,
            0x3f as core::ffi::c_int as WORD8,
            0x39 as core::ffi::c_int as WORD8,
        ],
    ],
    [
        [
            0x47 as core::ffi::c_int as WORD8,
            0x5f as core::ffi::c_int as WORD8,
            0x57 as core::ffi::c_int as WORD8,
            0x34 as core::ffi::c_int as WORD8,
            0x3c as core::ffi::c_int as WORD8,
            0x2e as core::ffi::c_int as WORD8,
            0x2e as core::ffi::c_int as WORD8,
            0x31 as core::ffi::c_int as WORD8,
        ],
        [
            0xfa as core::ffi::c_int as WORD8,
            0x13 as core::ffi::c_int as WORD8,
            0x23 as core::ffi::c_int as WORD8,
            0x4e as core::ffi::c_int as WORD8,
            0x44 as core::ffi::c_int as WORD8,
            0x7c as core::ffi::c_int as WORD8,
            0x34 as core::ffi::c_int as WORD8,
            0x38 as core::ffi::c_int as WORD8,
        ],
        [
            0x63 as core::ffi::c_int as WORD8,
            0x43 as core::ffi::c_int as WORD8,
            0x41 as core::ffi::c_int as WORD8,
            0x3d as core::ffi::c_int as WORD8,
            0x35 as core::ffi::c_int as WORD8,
            0x19 as core::ffi::c_int as WORD8,
            0x3d as core::ffi::c_int as WORD8,
            0x33 as core::ffi::c_int as WORD8,
        ],
    ],
];
#[no_mangle]
pub static mut ixheaacd_pred_coeff_table_2_mode_1: [[WORD8; 8]; 128] = [
    [
        0xcb as core::ffi::c_int as WORD8,
        0xd1 as core::ffi::c_int as WORD8,
        0xcc as core::ffi::c_int as WORD8,
        0xd2 as core::ffi::c_int as WORD8,
        0xe2 as core::ffi::c_int as WORD8,
        0xeb as core::ffi::c_int as WORD8,
        0xe7 as core::ffi::c_int as WORD8,
        0xe8 as core::ffi::c_int as WORD8,
    ],
    [
        0x80 as core::ffi::c_int as WORD8,
        0x80 as core::ffi::c_int as WORD8,
        0x80 as core::ffi::c_int as WORD8,
        0x80 as core::ffi::c_int as WORD8,
        0x80 as core::ffi::c_int as WORD8,
        0x80 as core::ffi::c_int as WORD8,
        0x80 as core::ffi::c_int as WORD8,
        0x80 as core::ffi::c_int as WORD8,
    ],
    [
        0x84 as core::ffi::c_int as WORD8,
        0x8c as core::ffi::c_int as WORD8,
        0x88 as core::ffi::c_int as WORD8,
        0x83 as core::ffi::c_int as WORD8,
        0x90 as core::ffi::c_int as WORD8,
        0x93 as core::ffi::c_int as WORD8,
        0x86 as core::ffi::c_int as WORD8,
        0x80 as core::ffi::c_int as WORD8,
    ],
    [
        0xd7 as core::ffi::c_int as WORD8,
        0xd8 as core::ffi::c_int as WORD8,
        0xc0 as core::ffi::c_int as WORD8,
        0xc7 as core::ffi::c_int as WORD8,
        0xcf as core::ffi::c_int as WORD8,
        0xe5 as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
    ],
    [
        0xa5 as core::ffi::c_int as WORD8,
        0xa6 as core::ffi::c_int as WORD8,
        0xaa as core::ffi::c_int as WORD8,
        0xa8 as core::ffi::c_int as WORD8,
        0xb0 as core::ffi::c_int as WORD8,
        0xb1 as core::ffi::c_int as WORD8,
        0xb8 as core::ffi::c_int as WORD8,
        0xb8 as core::ffi::c_int as WORD8,
    ],
    [
        0xd7 as core::ffi::c_int as WORD8,
        0xcb as core::ffi::c_int as WORD8,
        0xc1 as core::ffi::c_int as WORD8,
        0xc3 as core::ffi::c_int as WORD8,
        0xc5 as core::ffi::c_int as WORD8,
        0xc9 as core::ffi::c_int as WORD8,
        0xc9 as core::ffi::c_int as WORD8,
        0xce as core::ffi::c_int as WORD8,
    ],
    [
        0xca as core::ffi::c_int as WORD8,
        0xb5 as core::ffi::c_int as WORD8,
        0xb8 as core::ffi::c_int as WORD8,
        0xb3 as core::ffi::c_int as WORD8,
        0xac as core::ffi::c_int as WORD8,
        0xb6 as core::ffi::c_int as WORD8,
        0xbb as core::ffi::c_int as WORD8,
        0xb8 as core::ffi::c_int as WORD8,
    ],
    [
        0xc1 as core::ffi::c_int as WORD8,
        0xc4 as core::ffi::c_int as WORD8,
        0xc3 as core::ffi::c_int as WORD8,
        0xc5 as core::ffi::c_int as WORD8,
        0xc6 as core::ffi::c_int as WORD8,
        0xca as core::ffi::c_int as WORD8,
        0xca as core::ffi::c_int as WORD8,
        0xcb as core::ffi::c_int as WORD8,
    ],
    [
        0xe0 as core::ffi::c_int as WORD8,
        0xe1 as core::ffi::c_int as WORD8,
        0xd8 as core::ffi::c_int as WORD8,
        0xcd as core::ffi::c_int as WORD8,
        0xcb as core::ffi::c_int as WORD8,
        0xcb as core::ffi::c_int as WORD8,
        0xce as core::ffi::c_int as WORD8,
        0xcc as core::ffi::c_int as WORD8,
    ],
    [
        0xdb as core::ffi::c_int as WORD8,
        0xe1 as core::ffi::c_int as WORD8,
        0xdf as core::ffi::c_int as WORD8,
        0xdb as core::ffi::c_int as WORD8,
        0xdc as core::ffi::c_int as WORD8,
        0xd9 as core::ffi::c_int as WORD8,
        0xd9 as core::ffi::c_int as WORD8,
        0xd6 as core::ffi::c_int as WORD8,
    ],
    [
        0xe0 as core::ffi::c_int as WORD8,
        0xde as core::ffi::c_int as WORD8,
        0xdd as core::ffi::c_int as WORD8,
        0xdd as core::ffi::c_int as WORD8,
        0xe0 as core::ffi::c_int as WORD8,
        0xe3 as core::ffi::c_int as WORD8,
        0xe5 as core::ffi::c_int as WORD8,
        0xe6 as core::ffi::c_int as WORD8,
    ],
    [
        0xca as core::ffi::c_int as WORD8,
        0xd2 as core::ffi::c_int as WORD8,
        0xcd as core::ffi::c_int as WORD8,
        0xce as core::ffi::c_int as WORD8,
        0xd5 as core::ffi::c_int as WORD8,
        0xdb as core::ffi::c_int as WORD8,
        0xd9 as core::ffi::c_int as WORD8,
        0xdb as core::ffi::c_int as WORD8,
    ],
    [
        0xd2 as core::ffi::c_int as WORD8,
        0xe0 as core::ffi::c_int as WORD8,
        0xdb as core::ffi::c_int as WORD8,
        0xd5 as core::ffi::c_int as WORD8,
        0xdb as core::ffi::c_int as WORD8,
        0xde as core::ffi::c_int as WORD8,
        0xe3 as core::ffi::c_int as WORD8,
        0xe1 as core::ffi::c_int as WORD8,
    ],
    [
        0xe5 as core::ffi::c_int as WORD8,
        0xdb as core::ffi::c_int as WORD8,
        0xd0 as core::ffi::c_int as WORD8,
        0xd2 as core::ffi::c_int as WORD8,
        0xd8 as core::ffi::c_int as WORD8,
        0xdd as core::ffi::c_int as WORD8,
        0xdb as core::ffi::c_int as WORD8,
        0xdd as core::ffi::c_int as WORD8,
    ],
    [
        0xc0 as core::ffi::c_int as WORD8,
        0xb5 as core::ffi::c_int as WORD8,
        0xbf as core::ffi::c_int as WORD8,
        0xdd as core::ffi::c_int as WORD8,
        0xe3 as core::ffi::c_int as WORD8,
        0xdc as core::ffi::c_int as WORD8,
        0xdc as core::ffi::c_int as WORD8,
        0xe4 as core::ffi::c_int as WORD8,
    ],
    [
        0xdb as core::ffi::c_int as WORD8,
        0xce as core::ffi::c_int as WORD8,
        0xc6 as core::ffi::c_int as WORD8,
        0xcf as core::ffi::c_int as WORD8,
        0xcf as core::ffi::c_int as WORD8,
        0xd1 as core::ffi::c_int as WORD8,
        0xd3 as core::ffi::c_int as WORD8,
        0xd4 as core::ffi::c_int as WORD8,
    ],
    [
        0xc9 as core::ffi::c_int as WORD8,
        0xd7 as core::ffi::c_int as WORD8,
        0xda as core::ffi::c_int as WORD8,
        0xe2 as core::ffi::c_int as WORD8,
        0xe9 as core::ffi::c_int as WORD8,
        0xe7 as core::ffi::c_int as WORD8,
        0xdf as core::ffi::c_int as WORD8,
        0xdc as core::ffi::c_int as WORD8,
    ],
    [
        0xa as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
    ],
    [
        0x1e as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x33 as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
    ],
    [
        0xf0 as core::ffi::c_int as WORD8,
        0xda as core::ffi::c_int as WORD8,
        0xdc as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
    ],
    [
        0x9 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xe6 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
    ],
    [
        0x9 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xe6 as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
    ],
    [
        0xf2 as core::ffi::c_int as WORD8,
        0xe5 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
    ],
    [
        0x15 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
    ],
    [
        0xfa as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
    ],
    [
        0xfe as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
    ],
    [
        0xfa as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
    ],
    [
        0 as core::ffi::c_int as WORD8,
        0xf3 as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
    ],
    [
        0xea as core::ffi::c_int as WORD8,
        0xea as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
    ],
    [
        0x2 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
    ],
    [
        0xf6 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
    ],
    [
        0xf5 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
    ],
    [
        0x10 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
    ],
    [
        0xc as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
    ],
    [
        0xd as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0x2a as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x3b as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
    ],
    [
        0xfc as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
    ],
    [
        0x7 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0x2b as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
    ],
    [
        0x4 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
    ],
    [
        0 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
    ],
    [
        0xfb as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
    ],
    [
        0 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
    ],
    [
        0x4 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xeb as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
    ],
    [
        0x5 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
    ],
    [
        0x9 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
    ],
    [
        0x14 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
    ],
    [
        0x1 as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
    ],
    [
        0x12 as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
    ],
    [
        0x3 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
    ],
    [
        0x8 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
    ],
    [
        0x7 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
    ],
    [
        0x12 as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
    ],
    [
        0xc as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x2f as core::ffi::c_int as WORD8,
        0x33 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x28 as core::ffi::c_int as WORD8,
    ],
    [
        0xe as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
    ],
    [
        0x1a as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
    ],
    [
        0x1e as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x2a as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
    ],
    [
        0xf1 as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x28 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
    ],
    [
        0x8 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0xef as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
    ],
    [
        0xc as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
    ],
    [
        0xfb as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
    ],
    [
        0xf9 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
    ],
    [
        0x7 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
    ],
    [
        0xfe as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
    ],
    [
        0x9 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
    ],
    [
        0x7 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
    ],
    [
        0x4 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
    ],
    [
        0x3 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
    ],
    [
        0xfc as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x35 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
    ],
    [
        0x2 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
    ],
    [
        0xfa as core::ffi::c_int as WORD8,
        0xe9 as core::ffi::c_int as WORD8,
        0xd9 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
    ],
    [
        0xf1 as core::ffi::c_int as WORD8,
        0xe0 as core::ffi::c_int as WORD8,
        0xf0 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
    ],
    [
        0xe9 as core::ffi::c_int as WORD8,
        0xd4 as core::ffi::c_int as WORD8,
        0xd7 as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
    ],
    [
        0 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xe5 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
    ],
    [
        0xe0 as core::ffi::c_int as WORD8,
        0xda as core::ffi::c_int as WORD8,
        0xe5 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
    ],
    [
        0xe0 as core::ffi::c_int as WORD8,
        0xe2 as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
    ],
    [
        0xfc as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
    ],
    [
        0xfe as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xed as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
    ],
    [
        0xf3 as core::ffi::c_int as WORD8,
        0xef as core::ffi::c_int as WORD8,
        0xd0 as core::ffi::c_int as WORD8,
        0xe3 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
    ],
    [
        0xfa as core::ffi::c_int as WORD8,
        0xef as core::ffi::c_int as WORD8,
        0xea as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
    ],
    [
        0xf7 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xdb as core::ffi::c_int as WORD8,
        0xdf as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0xdd as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
    ],
    [
        0xfe as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0xdb as core::ffi::c_int as WORD8,
        0xe5 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0xed as core::ffi::c_int as WORD8,
    ],
    [
        0xf9 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xf3 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
    ],
    [
        0xef as core::ffi::c_int as WORD8,
        0xde as core::ffi::c_int as WORD8,
        0xd8 as core::ffi::c_int as WORD8,
        0xeb as core::ffi::c_int as WORD8,
        0xea as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
    ],
    [
        0xfb as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xec as core::ffi::c_int as WORD8,
        0xeb as core::ffi::c_int as WORD8,
        0xed as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xe8 as core::ffi::c_int as WORD8,
    ],
    [
        0xee as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0xf0 as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
    ],
    [
        0 as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
    ],
    [
        0xeb as core::ffi::c_int as WORD8,
        0xf0 as core::ffi::c_int as WORD8,
        0xdf as core::ffi::c_int as WORD8,
        0xe3 as core::ffi::c_int as WORD8,
        0xef as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
    ],
    [
        0xf7 as core::ffi::c_int as WORD8,
        0xf0 as core::ffi::c_int as WORD8,
        0xe6 as core::ffi::c_int as WORD8,
        0xe7 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
    ],
    [
        0xf1 as core::ffi::c_int as WORD8,
        0xe4 as core::ffi::c_int as WORD8,
        0xd8 as core::ffi::c_int as WORD8,
        0xea as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
    ],
    [
        0xff as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
    ],
    [
        0xdd as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xf0 as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xea as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
    ],
    [
        0xf0 as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
    ],
    [
        0xf1 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xe0 as core::ffi::c_int as WORD8,
        0xdf as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
    ],
    [
        0x2 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0xe5 as core::ffi::c_int as WORD8,
        0xdc as core::ffi::c_int as WORD8,
        0xe7 as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
    ],
    [
        0xec as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xec as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
    ],
    [
        0xf3 as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xe7 as core::ffi::c_int as WORD8,
        0xea as core::ffi::c_int as WORD8,
    ],
    [
        0xf7 as core::ffi::c_int as WORD8,
        0xf3 as core::ffi::c_int as WORD8,
        0xec as core::ffi::c_int as WORD8,
        0xea as core::ffi::c_int as WORD8,
        0xef as core::ffi::c_int as WORD8,
        0xf0 as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
    ],
    [
        0xeb as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xef as core::ffi::c_int as WORD8,
        0xf3 as core::ffi::c_int as WORD8,
        0xf3 as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
    ],
    [
        0x1 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xe1 as core::ffi::c_int as WORD8,
        0xeb as core::ffi::c_int as WORD8,
    ],
    [
        0xf5 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
    ],
    [
        0xf8 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
    ],
    [
        0x4 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
    ],
    [
        0x6 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
    ],
    [
        0xf5 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
    ],
    [
        0xf5 as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0x9 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
    ],
    [
        0xd7 as core::ffi::c_int as WORD8,
        0xe9 as core::ffi::c_int as WORD8,
        0xe8 as core::ffi::c_int as WORD8,
        0xec as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
    ],
    [
        0xec as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0xe9 as core::ffi::c_int as WORD8,
        0xdf as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0xe8 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
    ],
    [
        0xe6 as core::ffi::c_int as WORD8,
        0xe2 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
    ],
    [
        0xf1 as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
    ],
    [
        0xf6 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xe8 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
    ],
    [
        0xfe as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0xd0 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
    ],
    [
        0xf1 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
    ],
    [
        0xf4 as core::ffi::c_int as WORD8,
        0xea as core::ffi::c_int as WORD8,
        0xec as core::ffi::c_int as WORD8,
        0xf3 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
    ],
    [
        0xff as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
    ],
    [
        0 as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
    ],
    [
        0xf8 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xef as core::ffi::c_int as WORD8,
        0xec as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
    ],
    [
        0xeb as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xed as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
    ],
    [
        0xf7 as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xef as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
    ],
    [
        0xeb as core::ffi::c_int as WORD8,
        0xf0 as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
    ],
    [
        0xe8 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xe8 as core::ffi::c_int as WORD8,
        0xed as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
    ],
    [
        0xed as core::ffi::c_int as WORD8,
        0xeb as core::ffi::c_int as WORD8,
        0xe9 as core::ffi::c_int as WORD8,
        0xea as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xf4 as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
    ],
    [
        0xea as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0xef as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
    ],
    [
        0xfa as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xe4 as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0x1 as core::ffi::c_int as WORD8,
    ],
    [
        0xff as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
    ],
    [
        0xf4 as core::ffi::c_int as WORD8,
        0xec as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xf6 as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
    ],
    [
        0xe8 as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xe8 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
        0xe9 as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
    ],
    [
        0xe5 as core::ffi::c_int as WORD8,
        0xe9 as core::ffi::c_int as WORD8,
        0xf0 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0xef as core::ffi::c_int as WORD8,
        0xf3 as core::ffi::c_int as WORD8,
        0xf8 as core::ffi::c_int as WORD8,
    ],
    [
        0xf7 as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xfb as core::ffi::c_int as WORD8,
        0xf7 as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
        0xf9 as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xf0 as core::ffi::c_int as WORD8,
    ],
    [
        0xfd as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0xee as core::ffi::c_int as WORD8,
        0xf2 as core::ffi::c_int as WORD8,
        0xf5 as core::ffi::c_int as WORD8,
        0xf1 as core::ffi::c_int as WORD8,
        0xf3 as core::ffi::c_int as WORD8,
    ],
];
#[no_mangle]
pub static mut ixheaacd_pred_coeff_pvc_id_boundaries_2: [UWORD8; 2] = [
    16 as core::ffi::c_int as UWORD8,
    52 as core::ffi::c_int as UWORD8,
];
#[no_mangle]
pub static mut ixheaacd_q_factor_table_mode_2: [FLOAT32; 4] = [
    (1.0f64 / 128.0f64) as FLOAT32,
    (1.0f64 / 128.0f64) as FLOAT32,
    (1.0f64 / 64.0f64) as FLOAT32,
    (1.0f64 / 1.0f64) as FLOAT32,
];
#[no_mangle]
pub static mut ixheaacd_pred_coeff_table_1_mode_2: [[[WORD8; 6]; 3]; 3] = [
    [
        [
            0x11 as core::ffi::c_int as WORD8,
            0x27 as core::ffi::c_int as WORD8,
            0xf as core::ffi::c_int as WORD8,
            0xfd as core::ffi::c_int as WORD8,
            0x4 as core::ffi::c_int as WORD8,
            0xfc as core::ffi::c_int as WORD8,
        ],
        [
            0 as core::ffi::c_int as WORD8,
            0xbe as core::ffi::c_int as WORD8,
            0xe3 as core::ffi::c_int as WORD8,
            0xf4 as core::ffi::c_int as WORD8,
            0xdb as core::ffi::c_int as WORD8,
            0xf0 as core::ffi::c_int as WORD8,
        ],
        [
            0x9 as core::ffi::c_int as WORD8,
            0x1e as core::ffi::c_int as WORD8,
            0x18 as core::ffi::c_int as WORD8,
            0x1a as core::ffi::c_int as WORD8,
            0x21 as core::ffi::c_int as WORD8,
            0x1b as core::ffi::c_int as WORD8,
        ],
    ],
    [
        [
            0x16 as core::ffi::c_int as WORD8,
            0x28 as core::ffi::c_int as WORD8,
            0x2b as core::ffi::c_int as WORD8,
            0x29 as core::ffi::c_int as WORD8,
            0x25 as core::ffi::c_int as WORD8,
            0x32 as core::ffi::c_int as WORD8,
        ],
        [
            0xf2 as core::ffi::c_int as WORD8,
            0xe9 as core::ffi::c_int as WORD8,
            0xe4 as core::ffi::c_int as WORD8,
            0xe5 as core::ffi::c_int as WORD8,
            0xe2 as core::ffi::c_int as WORD8,
            0xd4 as core::ffi::c_int as WORD8,
        ],
        [
            0xe as core::ffi::c_int as WORD8,
            0xb as core::ffi::c_int as WORD8,
            0xc as core::ffi::c_int as WORD8,
            0xd as core::ffi::c_int as WORD8,
            0xd as core::ffi::c_int as WORD8,
            0xe as core::ffi::c_int as WORD8,
        ],
    ],
    [
        [
            0x2e as core::ffi::c_int as WORD8,
            0x3c as core::ffi::c_int as WORD8,
            0x20 as core::ffi::c_int as WORD8,
            0x16 as core::ffi::c_int as WORD8,
            0x1b as core::ffi::c_int as WORD8,
            0x1a as core::ffi::c_int as WORD8,
        ],
        [
            0xe4 as core::ffi::c_int as WORD8,
            0xc6 as core::ffi::c_int as WORD8,
            0xe5 as core::ffi::c_int as WORD8,
            0xf4 as core::ffi::c_int as WORD8,
            0xdc as core::ffi::c_int as WORD8,
            0xdc as core::ffi::c_int as WORD8,
        ],
        [
            0xf as core::ffi::c_int as WORD8,
            0x1b as core::ffi::c_int as WORD8,
            0x18 as core::ffi::c_int as WORD8,
            0x14 as core::ffi::c_int as WORD8,
            0x1e as core::ffi::c_int as WORD8,
            0x1a as core::ffi::c_int as WORD8,
        ],
    ],
];
#[no_mangle]
pub static mut ixheaacd_pred_coeff_table_2_mode_2: [[WORD8; 6]; 128] = [
    [
        0x26 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0xfa as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
    ],
    [
        0x1b as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
    ],
    [
        0x12 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
    ],
    [
        0x1e as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
    ],
    [
        0x24 as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
    ],
    [
        0xea as core::ffi::c_int as WORD8,
        0xed as core::ffi::c_int as WORD8,
        0xeb as core::ffi::c_int as WORD8,
        0xea as core::ffi::c_int as WORD8,
        0xec as core::ffi::c_int as WORD8,
        0xeb as core::ffi::c_int as WORD8,
    ],
    [
        0xfc as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0xfd as core::ffi::c_int as WORD8,
        0xfc as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
        0xfe as core::ffi::c_int as WORD8,
    ],
    [
        0xf as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0xa as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
    ],
    [
        0x22 as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
    ],
    [
        0x1c as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
    ],
    [
        0x10 as core::ffi::c_int as WORD8,
        0x8 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0xff as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
    ],
    [
        0x6 as core::ffi::c_int as WORD8,
        0x7 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x3 as core::ffi::c_int as WORD8,
        0x5 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
    ],
    [
        0x2a as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
    ],
    [
        0x19 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x2 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
        0 as core::ffi::c_int as WORD8,
        0x4 as core::ffi::c_int as WORD8,
    ],
    [
        0x18 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
    ],
    [
        0x21 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
    ],
    [
        0x3c as core::ffi::c_int as WORD8,
        0x35 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
        0x34 as core::ffi::c_int as WORD8,
    ],
    [
        0x3a as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x37 as core::ffi::c_int as WORD8,
        0x38 as core::ffi::c_int as WORD8,
        0x33 as core::ffi::c_int as WORD8,
        0x31 as core::ffi::c_int as WORD8,
    ],
    [
        0x37 as core::ffi::c_int as WORD8,
        0x34 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x35 as core::ffi::c_int as WORD8,
        0x34 as core::ffi::c_int as WORD8,
    ],
    [
        0x34 as core::ffi::c_int as WORD8,
        0x2e as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
        0x31 as core::ffi::c_int as WORD8,
        0x34 as core::ffi::c_int as WORD8,
        0x31 as core::ffi::c_int as WORD8,
    ],
    [
        0x36 as core::ffi::c_int as WORD8,
        0x33 as core::ffi::c_int as WORD8,
        0x2f as core::ffi::c_int as WORD8,
        0x2f as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
        0x2f as core::ffi::c_int as WORD8,
    ],
    [
        0x35 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x2f as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
        0x2f as core::ffi::c_int as WORD8,
        0x2c as core::ffi::c_int as WORD8,
    ],
    [
        0x2e as core::ffi::c_int as WORD8,
        0x2b as core::ffi::c_int as WORD8,
        0x2f as core::ffi::c_int as WORD8,
        0x34 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
    ],
    [
        0x3f as core::ffi::c_int as WORD8,
        0x39 as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
        0x28 as core::ffi::c_int as WORD8,
        0x29 as core::ffi::c_int as WORD8,
        0x29 as core::ffi::c_int as WORD8,
    ],
    [
        0x3c as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
        0x37 as core::ffi::c_int as WORD8,
        0x39 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
    ],
    [
        0x37 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
        0x2b as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
    ],
    [
        0x44 as core::ffi::c_int as WORD8,
        0x38 as core::ffi::c_int as WORD8,
        0x2f as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
    ],
    [
        0x38 as core::ffi::c_int as WORD8,
        0x2b as core::ffi::c_int as WORD8,
        0x2c as core::ffi::c_int as WORD8,
        0x2c as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
    ],
    [
        0x37 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
        0x2f as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
    ],
    [
        0x3c as core::ffi::c_int as WORD8,
        0x39 as core::ffi::c_int as WORD8,
        0x29 as core::ffi::c_int as WORD8,
        0x2e as core::ffi::c_int as WORD8,
        0x38 as core::ffi::c_int as WORD8,
        0x37 as core::ffi::c_int as WORD8,
    ],
    [
        0x3b as core::ffi::c_int as WORD8,
        0x3a as core::ffi::c_int as WORD8,
        0x35 as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
        0x31 as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
    ],
    [
        0x32 as core::ffi::c_int as WORD8,
        0x31 as core::ffi::c_int as WORD8,
        0x2f as core::ffi::c_int as WORD8,
        0x2c as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x28 as core::ffi::c_int as WORD8,
    ],
    [
        0x2c as core::ffi::c_int as WORD8,
        0x31 as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
    ],
    [
        0x35 as core::ffi::c_int as WORD8,
        0x34 as core::ffi::c_int as WORD8,
        0x34 as core::ffi::c_int as WORD8,
        0x34 as core::ffi::c_int as WORD8,
        0x35 as core::ffi::c_int as WORD8,
        0x33 as core::ffi::c_int as WORD8,
    ],
    [
        0x34 as core::ffi::c_int as WORD8,
        0x38 as core::ffi::c_int as WORD8,
        0x3b as core::ffi::c_int as WORD8,
        0x3c as core::ffi::c_int as WORD8,
        0x3e as core::ffi::c_int as WORD8,
        0x3a as core::ffi::c_int as WORD8,
    ],
    [
        0x3e as core::ffi::c_int as WORD8,
        0x3c as core::ffi::c_int as WORD8,
        0x3b as core::ffi::c_int as WORD8,
        0x3a as core::ffi::c_int as WORD8,
        0x3c as core::ffi::c_int as WORD8,
        0x39 as core::ffi::c_int as WORD8,
    ],
    [
        0x3d as core::ffi::c_int as WORD8,
        0x41 as core::ffi::c_int as WORD8,
        0x46 as core::ffi::c_int as WORD8,
        0x41 as core::ffi::c_int as WORD8,
        0x3d as core::ffi::c_int as WORD8,
        0x38 as core::ffi::c_int as WORD8,
    ],
    [
        0x44 as core::ffi::c_int as WORD8,
        0x41 as core::ffi::c_int as WORD8,
        0x40 as core::ffi::c_int as WORD8,
        0x3e as core::ffi::c_int as WORD8,
        0x3f as core::ffi::c_int as WORD8,
        0x3a as core::ffi::c_int as WORD8,
    ],
    [
        0x47 as core::ffi::c_int as WORD8,
        0x47 as core::ffi::c_int as WORD8,
        0x47 as core::ffi::c_int as WORD8,
        0x42 as core::ffi::c_int as WORD8,
        0x44 as core::ffi::c_int as WORD8,
        0x40 as core::ffi::c_int as WORD8,
    ],
    [
        0x4c as core::ffi::c_int as WORD8,
        0x4a as core::ffi::c_int as WORD8,
        0x4a as core::ffi::c_int as WORD8,
        0x46 as core::ffi::c_int as WORD8,
        0x49 as core::ffi::c_int as WORD8,
        0x45 as core::ffi::c_int as WORD8,
    ],
    [
        0x53 as core::ffi::c_int as WORD8,
        0x52 as core::ffi::c_int as WORD8,
        0x52 as core::ffi::c_int as WORD8,
        0x4c as core::ffi::c_int as WORD8,
        0x4e as core::ffi::c_int as WORD8,
        0x49 as core::ffi::c_int as WORD8,
    ],
    [
        0x41 as core::ffi::c_int as WORD8,
        0x3d as core::ffi::c_int as WORD8,
        0x39 as core::ffi::c_int as WORD8,
        0x2c as core::ffi::c_int as WORD8,
        0x2e as core::ffi::c_int as WORD8,
        0x2e as core::ffi::c_int as WORD8,
    ],
    [
        0x2d as core::ffi::c_int as WORD8,
        0x37 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
        0x28 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
    ],
    [
        0x3b as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
        0x2e as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x29 as core::ffi::c_int as WORD8,
    ],
    [
        0x40 as core::ffi::c_int as WORD8,
        0x39 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
        0x35 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
    ],
    [
        0x30 as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x2e as core::ffi::c_int as WORD8,
        0x31 as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
    ],
    [
        0x38 as core::ffi::c_int as WORD8,
        0x3d as core::ffi::c_int as WORD8,
        0x3b as core::ffi::c_int as WORD8,
        0x37 as core::ffi::c_int as WORD8,
        0x35 as core::ffi::c_int as WORD8,
        0x34 as core::ffi::c_int as WORD8,
    ],
    [
        0x44 as core::ffi::c_int as WORD8,
        0x3d as core::ffi::c_int as WORD8,
        0x3c as core::ffi::c_int as WORD8,
        0x38 as core::ffi::c_int as WORD8,
        0x37 as core::ffi::c_int as WORD8,
        0x33 as core::ffi::c_int as WORD8,
    ],
    [
        0x3a as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
        0x37 as core::ffi::c_int as WORD8,
        0x37 as core::ffi::c_int as WORD8,
        0x39 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
    ],
    [
        0x32 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
        0x37 as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
        0x2e as core::ffi::c_int as WORD8,
        0x2a as core::ffi::c_int as WORD8,
    ],
    [
        0x3c as core::ffi::c_int as WORD8,
        0x33 as core::ffi::c_int as WORD8,
        0x33 as core::ffi::c_int as WORD8,
        0x31 as core::ffi::c_int as WORD8,
        0x33 as core::ffi::c_int as WORD8,
        0x30 as core::ffi::c_int as WORD8,
    ],
    [
        0x30 as core::ffi::c_int as WORD8,
        0x31 as core::ffi::c_int as WORD8,
        0x36 as core::ffi::c_int as WORD8,
        0x37 as core::ffi::c_int as WORD8,
        0x38 as core::ffi::c_int as WORD8,
        0x34 as core::ffi::c_int as WORD8,
    ],
    [
        0x26 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x2e as core::ffi::c_int as WORD8,
        0x29 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
    ],
    [
        0x14 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
    ],
    [
        0x38 as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x2b as core::ffi::c_int as WORD8,
    ],
    [
        0x30 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x2b as core::ffi::c_int as WORD8,
    ],
    [
        0x24 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
    ],
    [
        0x27 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x2a as core::ffi::c_int as WORD8,
    ],
    [
        0x2f as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x2a as core::ffi::c_int as WORD8,
        0x32 as core::ffi::c_int as WORD8,
    ],
    [
        0x31 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x28 as core::ffi::c_int as WORD8,
    ],
    [
        0x2a as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
    ],
    [
        0x27 as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
    ],
    [
        0x2f as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
    ],
    [
        0x1e as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
    ],
    [
        0x31 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
    ],
    [
        0x2d as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
    ],
    [
        0x25 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
    ],
    [
        0x2f as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
    ],
    [
        0x21 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
    ],
    [
        0x23 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x28 as core::ffi::c_int as WORD8,
        0x29 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
    ],
    [
        0x2e as core::ffi::c_int as WORD8,
        0x2a as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
    ],
    [
        0x31 as core::ffi::c_int as WORD8,
        0x2c as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
    ],
    [
        0x26 as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
    ],
    [
        0x29 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
    ],
    [
        0x1d as core::ffi::c_int as WORD8,
        0x6 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
    ],
    [
        0x2b as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
    ],
    [
        0x27 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0xc as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
    ],
    [
        0x29 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
    ],
    [
        0x20 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
    ],
    [
        0x27 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x10 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
    ],
    [
        0x26 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x28 as core::ffi::c_int as WORD8,
    ],
    [
        0x1a as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x29 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
    ],
    [
        0x1d as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
    ],
    [
        0x1e as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
    ],
    [
        0x16 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
    ],
    [
        0x20 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
    ],
    [
        0x1f as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
    ],
    [
        0x20 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
    ],
    [
        0x23 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
    ],
    [
        0x26 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
    ],
    [
        0x23 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
    ],
    [
        0x29 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
    ],
    [
        0x26 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
    ],
    [
        0x29 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x29 as core::ffi::c_int as WORD8,
    ],
    [
        0x2b as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
    ],
    [
        0x29 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0xe as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
    ],
    [
        0x32 as core::ffi::c_int as WORD8,
        0x29 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
    ],
    [
        0x1e as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
    ],
    [
        0x24 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
    ],
    [
        0x2c as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
    ],
    [
        0x24 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x2b as core::ffi::c_int as WORD8,
        0x2c as core::ffi::c_int as WORD8,
    ],
    [
        0x28 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x28 as core::ffi::c_int as WORD8,
        0x2d as core::ffi::c_int as WORD8,
    ],
    [
        0x23 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x29 as core::ffi::c_int as WORD8,
    ],
    [
        0x1b as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
    ],
    [
        0x1e as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
    ],
    [
        0x2b as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
    ],
    [
        0x1c as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
    ],
    [
        0x21 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
    ],
    [
        0x1d as core::ffi::c_int as WORD8,
        0xb as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x11 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
    ],
    [
        0x18 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
    ],
    [
        0x16 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
    ],
    [
        0x30 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
    ],
    [
        0x1b as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
    ],
    [
        0x32 as core::ffi::c_int as WORD8,
        0x2b as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
    ],
    [
        0x28 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
    ],
    [
        0x32 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
    ],
    [
        0x22 as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
    ],
    [
        0x27 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x2a as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
    ],
    [
        0x1e as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0xd as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x1d as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
    ],
    [
        0x28 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0x25 as core::ffi::c_int as WORD8,
    ],
    [
        0x2b as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x13 as core::ffi::c_int as WORD8,
        0x14 as core::ffi::c_int as WORD8,
    ],
    [
        0x25 as core::ffi::c_int as WORD8,
        0x2b as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
    ],
    [
        0x27 as core::ffi::c_int as WORD8,
        0x1b as core::ffi::c_int as WORD8,
        0x16 as core::ffi::c_int as WORD8,
        0x17 as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
    ],
    [
        0x29 as core::ffi::c_int as WORD8,
        0x26 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x1e as core::ffi::c_int as WORD8,
        0x28 as core::ffi::c_int as WORD8,
    ],
    [
        0x24 as core::ffi::c_int as WORD8,
        0x1c as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
        0x1a as core::ffi::c_int as WORD8,
        0x18 as core::ffi::c_int as WORD8,
        0x19 as core::ffi::c_int as WORD8,
    ],
    [
        0x2d as core::ffi::c_int as WORD8,
        0x15 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x2b as core::ffi::c_int as WORD8,
        0x24 as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
    ],
    [
        0x2c as core::ffi::c_int as WORD8,
        0x12 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x23 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x20 as core::ffi::c_int as WORD8,
    ],
    [
        0x25 as core::ffi::c_int as WORD8,
        0xf as core::ffi::c_int as WORD8,
        0x22 as core::ffi::c_int as WORD8,
        0x27 as core::ffi::c_int as WORD8,
        0x1f as core::ffi::c_int as WORD8,
        0x21 as core::ffi::c_int as WORD8,
    ],
];
