pub type WORD16 = core::ffi::c_short;
pub type WORD32 = core::ffi::c_int;
#[derive(Copy, Clone)]
#[repr(C)]
pub struct ixheaacd_misc_tables {
    pub trig_data: [WORD16; 513],
    pub sine_table8_16: [WORD16; 8],
    pub log_dual_is_table: [WORD16; 65],
    pub down_mix_martix: [[[WORD32; 8]; 2]; 4],
    pub cc_gain_scale: [WORD32; 4],
    pub inv_table: [WORD16; 256],
    pub sqrt_table: [WORD16; 257],
    pub dummy: WORD32,
    pub start_band: [[WORD32; 16]; 10],
    pub stop_band: [[WORD32; 16]; 10],
    pub stop_freq_table_fs40k_2: [WORD32; 14],
    pub stop_freq_table_fs40k_4: [WORD32; 14],
}
#[no_mangle]
pub static mut ixheaacd_str_fft_n_transcendent_tables: ixheaacd_misc_tables = {
    let mut init = ixheaacd_misc_tables {
        trig_data: [
            0 as core::ffi::c_int as WORD16,
            0x65 as core::ffi::c_int as WORD16,
            0xc9 as core::ffi::c_int as WORD16,
            0x12e as core::ffi::c_int as WORD16,
            0x192 as core::ffi::c_int as WORD16,
            0x1f7 as core::ffi::c_int as WORD16,
            0x25b as core::ffi::c_int as WORD16,
            0x2c0 as core::ffi::c_int as WORD16,
            0x324 as core::ffi::c_int as WORD16,
            0x389 as core::ffi::c_int as WORD16,
            0x3ed as core::ffi::c_int as WORD16,
            0x452 as core::ffi::c_int as WORD16,
            0x4b6 as core::ffi::c_int as WORD16,
            0x51b as core::ffi::c_int as WORD16,
            0x57f as core::ffi::c_int as WORD16,
            0x5e3 as core::ffi::c_int as WORD16,
            0x648 as core::ffi::c_int as WORD16,
            0x6ac as core::ffi::c_int as WORD16,
            0x711 as core::ffi::c_int as WORD16,
            0x775 as core::ffi::c_int as WORD16,
            0x7d9 as core::ffi::c_int as WORD16,
            0x83e as core::ffi::c_int as WORD16,
            0x8a2 as core::ffi::c_int as WORD16,
            0x906 as core::ffi::c_int as WORD16,
            0x96b as core::ffi::c_int as WORD16,
            0x9cf as core::ffi::c_int as WORD16,
            0xa33 as core::ffi::c_int as WORD16,
            0xa97 as core::ffi::c_int as WORD16,
            0xafb as core::ffi::c_int as WORD16,
            0xb60 as core::ffi::c_int as WORD16,
            0xbc4 as core::ffi::c_int as WORD16,
            0xc28 as core::ffi::c_int as WORD16,
            0xc8c as core::ffi::c_int as WORD16,
            0xcf0 as core::ffi::c_int as WORD16,
            0xd54 as core::ffi::c_int as WORD16,
            0xdb8 as core::ffi::c_int as WORD16,
            0xe1c as core::ffi::c_int as WORD16,
            0xe80 as core::ffi::c_int as WORD16,
            0xee4 as core::ffi::c_int as WORD16,
            0xf47 as core::ffi::c_int as WORD16,
            0xfab as core::ffi::c_int as WORD16,
            0x100f as core::ffi::c_int as WORD16,
            0x1073 as core::ffi::c_int as WORD16,
            0x10d6 as core::ffi::c_int as WORD16,
            0x113a as core::ffi::c_int as WORD16,
            0x119e as core::ffi::c_int as WORD16,
            0x1201 as core::ffi::c_int as WORD16,
            0x1265 as core::ffi::c_int as WORD16,
            0x12c8 as core::ffi::c_int as WORD16,
            0x132b as core::ffi::c_int as WORD16,
            0x138f as core::ffi::c_int as WORD16,
            0x13f2 as core::ffi::c_int as WORD16,
            0x1455 as core::ffi::c_int as WORD16,
            0x14b9 as core::ffi::c_int as WORD16,
            0x151c as core::ffi::c_int as WORD16,
            0x157f as core::ffi::c_int as WORD16,
            0x15e2 as core::ffi::c_int as WORD16,
            0x1645 as core::ffi::c_int as WORD16,
            0x16a8 as core::ffi::c_int as WORD16,
            0x170b as core::ffi::c_int as WORD16,
            0x176e as core::ffi::c_int as WORD16,
            0x17d1 as core::ffi::c_int as WORD16,
            0x1833 as core::ffi::c_int as WORD16,
            0x1896 as core::ffi::c_int as WORD16,
            0x18f9 as core::ffi::c_int as WORD16,
            0x195b as core::ffi::c_int as WORD16,
            0x19be as core::ffi::c_int as WORD16,
            0x1a20 as core::ffi::c_int as WORD16,
            0x1a83 as core::ffi::c_int as WORD16,
            0x1ae5 as core::ffi::c_int as WORD16,
            0x1b47 as core::ffi::c_int as WORD16,
            0x1ba9 as core::ffi::c_int as WORD16,
            0x1c0c as core::ffi::c_int as WORD16,
            0x1c6e as core::ffi::c_int as WORD16,
            0x1cd0 as core::ffi::c_int as WORD16,
            0x1d31 as core::ffi::c_int as WORD16,
            0x1d93 as core::ffi::c_int as WORD16,
            0x1df5 as core::ffi::c_int as WORD16,
            0x1e57 as core::ffi::c_int as WORD16,
            0x1eb8 as core::ffi::c_int as WORD16,
            0x1f1a as core::ffi::c_int as WORD16,
            0x1f7b as core::ffi::c_int as WORD16,
            0x1fdd as core::ffi::c_int as WORD16,
            0x203e as core::ffi::c_int as WORD16,
            0x209f as core::ffi::c_int as WORD16,
            0x2101 as core::ffi::c_int as WORD16,
            0x2162 as core::ffi::c_int as WORD16,
            0x21c3 as core::ffi::c_int as WORD16,
            0x2224 as core::ffi::c_int as WORD16,
            0x2284 as core::ffi::c_int as WORD16,
            0x22e5 as core::ffi::c_int as WORD16,
            0x2346 as core::ffi::c_int as WORD16,
            0x23a7 as core::ffi::c_int as WORD16,
            0x2407 as core::ffi::c_int as WORD16,
            0x2467 as core::ffi::c_int as WORD16,
            0x24c8 as core::ffi::c_int as WORD16,
            0x2528 as core::ffi::c_int as WORD16,
            0x2588 as core::ffi::c_int as WORD16,
            0x25e8 as core::ffi::c_int as WORD16,
            0x2648 as core::ffi::c_int as WORD16,
            0x26a8 as core::ffi::c_int as WORD16,
            0x2708 as core::ffi::c_int as WORD16,
            0x2768 as core::ffi::c_int as WORD16,
            0x27c7 as core::ffi::c_int as WORD16,
            0x2827 as core::ffi::c_int as WORD16,
            0x2886 as core::ffi::c_int as WORD16,
            0x28e5 as core::ffi::c_int as WORD16,
            0x2945 as core::ffi::c_int as WORD16,
            0x29a4 as core::ffi::c_int as WORD16,
            0x2a03 as core::ffi::c_int as WORD16,
            0x2a62 as core::ffi::c_int as WORD16,
            0x2ac1 as core::ffi::c_int as WORD16,
            0x2b1f as core::ffi::c_int as WORD16,
            0x2b7e as core::ffi::c_int as WORD16,
            0x2bdc as core::ffi::c_int as WORD16,
            0x2c3b as core::ffi::c_int as WORD16,
            0x2c99 as core::ffi::c_int as WORD16,
            0x2cf7 as core::ffi::c_int as WORD16,
            0x2d55 as core::ffi::c_int as WORD16,
            0x2db3 as core::ffi::c_int as WORD16,
            0x2e11 as core::ffi::c_int as WORD16,
            0x2e6f as core::ffi::c_int as WORD16,
            0x2ecc as core::ffi::c_int as WORD16,
            0x2f2a as core::ffi::c_int as WORD16,
            0x2f87 as core::ffi::c_int as WORD16,
            0x2fe5 as core::ffi::c_int as WORD16,
            0x3042 as core::ffi::c_int as WORD16,
            0x309f as core::ffi::c_int as WORD16,
            0x30fc as core::ffi::c_int as WORD16,
            0x3159 as core::ffi::c_int as WORD16,
            0x31b5 as core::ffi::c_int as WORD16,
            0x3212 as core::ffi::c_int as WORD16,
            0x326e as core::ffi::c_int as WORD16,
            0x32cb as core::ffi::c_int as WORD16,
            0x3327 as core::ffi::c_int as WORD16,
            0x3383 as core::ffi::c_int as WORD16,
            0x33df as core::ffi::c_int as WORD16,
            0x343b as core::ffi::c_int as WORD16,
            0x3497 as core::ffi::c_int as WORD16,
            0x34f2 as core::ffi::c_int as WORD16,
            0x354e as core::ffi::c_int as WORD16,
            0x35a9 as core::ffi::c_int as WORD16,
            0x3604 as core::ffi::c_int as WORD16,
            0x365f as core::ffi::c_int as WORD16,
            0x36ba as core::ffi::c_int as WORD16,
            0x3715 as core::ffi::c_int as WORD16,
            0x3770 as core::ffi::c_int as WORD16,
            0x37ca as core::ffi::c_int as WORD16,
            0x3825 as core::ffi::c_int as WORD16,
            0x387f as core::ffi::c_int as WORD16,
            0x38d9 as core::ffi::c_int as WORD16,
            0x3933 as core::ffi::c_int as WORD16,
            0x398d as core::ffi::c_int as WORD16,
            0x39e7 as core::ffi::c_int as WORD16,
            0x3a40 as core::ffi::c_int as WORD16,
            0x3a9a as core::ffi::c_int as WORD16,
            0x3af3 as core::ffi::c_int as WORD16,
            0x3b4c as core::ffi::c_int as WORD16,
            0x3ba5 as core::ffi::c_int as WORD16,
            0x3bfe as core::ffi::c_int as WORD16,
            0x3c57 as core::ffi::c_int as WORD16,
            0x3caf as core::ffi::c_int as WORD16,
            0x3d08 as core::ffi::c_int as WORD16,
            0x3d60 as core::ffi::c_int as WORD16,
            0x3db8 as core::ffi::c_int as WORD16,
            0x3e10 as core::ffi::c_int as WORD16,
            0x3e68 as core::ffi::c_int as WORD16,
            0x3ec0 as core::ffi::c_int as WORD16,
            0x3f17 as core::ffi::c_int as WORD16,
            0x3f6f as core::ffi::c_int as WORD16,
            0x3fc6 as core::ffi::c_int as WORD16,
            0x401d as core::ffi::c_int as WORD16,
            0x4074 as core::ffi::c_int as WORD16,
            0x40cb as core::ffi::c_int as WORD16,
            0x4121 as core::ffi::c_int as WORD16,
            0x4178 as core::ffi::c_int as WORD16,
            0x41ce as core::ffi::c_int as WORD16,
            0x4224 as core::ffi::c_int as WORD16,
            0x427a as core::ffi::c_int as WORD16,
            0x42d0 as core::ffi::c_int as WORD16,
            0x4326 as core::ffi::c_int as WORD16,
            0x437b as core::ffi::c_int as WORD16,
            0x43d1 as core::ffi::c_int as WORD16,
            0x4426 as core::ffi::c_int as WORD16,
            0x447b as core::ffi::c_int as WORD16,
            0x44d0 as core::ffi::c_int as WORD16,
            0x4524 as core::ffi::c_int as WORD16,
            0x4579 as core::ffi::c_int as WORD16,
            0x45cd as core::ffi::c_int as WORD16,
            0x4621 as core::ffi::c_int as WORD16,
            0x4675 as core::ffi::c_int as WORD16,
            0x46c9 as core::ffi::c_int as WORD16,
            0x471d as core::ffi::c_int as WORD16,
            0x4770 as core::ffi::c_int as WORD16,
            0x47c4 as core::ffi::c_int as WORD16,
            0x4817 as core::ffi::c_int as WORD16,
            0x486a as core::ffi::c_int as WORD16,
            0x48bd as core::ffi::c_int as WORD16,
            0x490f as core::ffi::c_int as WORD16,
            0x4962 as core::ffi::c_int as WORD16,
            0x49b4 as core::ffi::c_int as WORD16,
            0x4a06 as core::ffi::c_int as WORD16,
            0x4a58 as core::ffi::c_int as WORD16,
            0x4aaa as core::ffi::c_int as WORD16,
            0x4afb as core::ffi::c_int as WORD16,
            0x4b4d as core::ffi::c_int as WORD16,
            0x4b9e as core::ffi::c_int as WORD16,
            0x4bef as core::ffi::c_int as WORD16,
            0x4c40 as core::ffi::c_int as WORD16,
            0x4c91 as core::ffi::c_int as WORD16,
            0x4ce1 as core::ffi::c_int as WORD16,
            0x4d31 as core::ffi::c_int as WORD16,
            0x4d81 as core::ffi::c_int as WORD16,
            0x4dd1 as core::ffi::c_int as WORD16,
            0x4e21 as core::ffi::c_int as WORD16,
            0x4e71 as core::ffi::c_int as WORD16,
            0x4ec0 as core::ffi::c_int as WORD16,
            0x4f0f as core::ffi::c_int as WORD16,
            0x4f5e as core::ffi::c_int as WORD16,
            0x4fad as core::ffi::c_int as WORD16,
            0x4ffb as core::ffi::c_int as WORD16,
            0x504a as core::ffi::c_int as WORD16,
            0x5098 as core::ffi::c_int as WORD16,
            0x50e6 as core::ffi::c_int as WORD16,
            0x5134 as core::ffi::c_int as WORD16,
            0x5181 as core::ffi::c_int as WORD16,
            0x51cf as core::ffi::c_int as WORD16,
            0x521c as core::ffi::c_int as WORD16,
            0x5269 as core::ffi::c_int as WORD16,
            0x52b6 as core::ffi::c_int as WORD16,
            0x5303 as core::ffi::c_int as WORD16,
            0x534f as core::ffi::c_int as WORD16,
            0x539b as core::ffi::c_int as WORD16,
            0x53e7 as core::ffi::c_int as WORD16,
            0x5433 as core::ffi::c_int as WORD16,
            0x547f as core::ffi::c_int as WORD16,
            0x54ca as core::ffi::c_int as WORD16,
            0x5515 as core::ffi::c_int as WORD16,
            0x5560 as core::ffi::c_int as WORD16,
            0x55ab as core::ffi::c_int as WORD16,
            0x55f6 as core::ffi::c_int as WORD16,
            0x5640 as core::ffi::c_int as WORD16,
            0x568a as core::ffi::c_int as WORD16,
            0x56d4 as core::ffi::c_int as WORD16,
            0x571e as core::ffi::c_int as WORD16,
            0x5767 as core::ffi::c_int as WORD16,
            0x57b1 as core::ffi::c_int as WORD16,
            0x57fa as core::ffi::c_int as WORD16,
            0x5843 as core::ffi::c_int as WORD16,
            0x588c as core::ffi::c_int as WORD16,
            0x58d4 as core::ffi::c_int as WORD16,
            0x591c as core::ffi::c_int as WORD16,
            0x5964 as core::ffi::c_int as WORD16,
            0x59ac as core::ffi::c_int as WORD16,
            0x59f4 as core::ffi::c_int as WORD16,
            0x5a3b as core::ffi::c_int as WORD16,
            0x5a82 as core::ffi::c_int as WORD16,
            0x5ac9 as core::ffi::c_int as WORD16,
            0x5b10 as core::ffi::c_int as WORD16,
            0x5b57 as core::ffi::c_int as WORD16,
            0x5b9d as core::ffi::c_int as WORD16,
            0x5be3 as core::ffi::c_int as WORD16,
            0x5c29 as core::ffi::c_int as WORD16,
            0x5c6f as core::ffi::c_int as WORD16,
            0x5cb4 as core::ffi::c_int as WORD16,
            0x5cf9 as core::ffi::c_int as WORD16,
            0x5d3e as core::ffi::c_int as WORD16,
            0x5d83 as core::ffi::c_int as WORD16,
            0x5dc8 as core::ffi::c_int as WORD16,
            0x5e0c as core::ffi::c_int as WORD16,
            0x5e50 as core::ffi::c_int as WORD16,
            0x5e94 as core::ffi::c_int as WORD16,
            0x5ed7 as core::ffi::c_int as WORD16,
            0x5f1b as core::ffi::c_int as WORD16,
            0x5f5e as core::ffi::c_int as WORD16,
            0x5fa1 as core::ffi::c_int as WORD16,
            0x5fe4 as core::ffi::c_int as WORD16,
            0x6026 as core::ffi::c_int as WORD16,
            0x6068 as core::ffi::c_int as WORD16,
            0x60aa as core::ffi::c_int as WORD16,
            0x60ec as core::ffi::c_int as WORD16,
            0x612e as core::ffi::c_int as WORD16,
            0x616f as core::ffi::c_int as WORD16,
            0x61b0 as core::ffi::c_int as WORD16,
            0x61f1 as core::ffi::c_int as WORD16,
            0x6232 as core::ffi::c_int as WORD16,
            0x6272 as core::ffi::c_int as WORD16,
            0x62b2 as core::ffi::c_int as WORD16,
            0x62f2 as core::ffi::c_int as WORD16,
            0x6332 as core::ffi::c_int as WORD16,
            0x6371 as core::ffi::c_int as WORD16,
            0x63b0 as core::ffi::c_int as WORD16,
            0x63ef as core::ffi::c_int as WORD16,
            0x642e as core::ffi::c_int as WORD16,
            0x646c as core::ffi::c_int as WORD16,
            0x64ab as core::ffi::c_int as WORD16,
            0x64e9 as core::ffi::c_int as WORD16,
            0x6526 as core::ffi::c_int as WORD16,
            0x6564 as core::ffi::c_int as WORD16,
            0x65a1 as core::ffi::c_int as WORD16,
            0x65de as core::ffi::c_int as WORD16,
            0x661b as core::ffi::c_int as WORD16,
            0x6657 as core::ffi::c_int as WORD16,
            0x6693 as core::ffi::c_int as WORD16,
            0x66d0 as core::ffi::c_int as WORD16,
            0x670b as core::ffi::c_int as WORD16,
            0x6747 as core::ffi::c_int as WORD16,
            0x6782 as core::ffi::c_int as WORD16,
            0x67bd as core::ffi::c_int as WORD16,
            0x67f8 as core::ffi::c_int as WORD16,
            0x6832 as core::ffi::c_int as WORD16,
            0x686d as core::ffi::c_int as WORD16,
            0x68a7 as core::ffi::c_int as WORD16,
            0x68e0 as core::ffi::c_int as WORD16,
            0x691a as core::ffi::c_int as WORD16,
            0x6953 as core::ffi::c_int as WORD16,
            0x698c as core::ffi::c_int as WORD16,
            0x69c5 as core::ffi::c_int as WORD16,
            0x69fd as core::ffi::c_int as WORD16,
            0x6a36 as core::ffi::c_int as WORD16,
            0x6a6e as core::ffi::c_int as WORD16,
            0x6aa5 as core::ffi::c_int as WORD16,
            0x6add as core::ffi::c_int as WORD16,
            0x6b14 as core::ffi::c_int as WORD16,
            0x6b4b as core::ffi::c_int as WORD16,
            0x6b82 as core::ffi::c_int as WORD16,
            0x6bb8 as core::ffi::c_int as WORD16,
            0x6bee as core::ffi::c_int as WORD16,
            0x6c24 as core::ffi::c_int as WORD16,
            0x6c5a as core::ffi::c_int as WORD16,
            0x6c8f as core::ffi::c_int as WORD16,
            0x6cc4 as core::ffi::c_int as WORD16,
            0x6cf9 as core::ffi::c_int as WORD16,
            0x6d2e as core::ffi::c_int as WORD16,
            0x6d62 as core::ffi::c_int as WORD16,
            0x6d96 as core::ffi::c_int as WORD16,
            0x6dca as core::ffi::c_int as WORD16,
            0x6dfe as core::ffi::c_int as WORD16,
            0x6e31 as core::ffi::c_int as WORD16,
            0x6e64 as core::ffi::c_int as WORD16,
            0x6e97 as core::ffi::c_int as WORD16,
            0x6ec9 as core::ffi::c_int as WORD16,
            0x6efb as core::ffi::c_int as WORD16,
            0x6f2d as core::ffi::c_int as WORD16,
            0x6f5f as core::ffi::c_int as WORD16,
            0x6f90 as core::ffi::c_int as WORD16,
            0x6fc2 as core::ffi::c_int as WORD16,
            0x6ff2 as core::ffi::c_int as WORD16,
            0x7023 as core::ffi::c_int as WORD16,
            0x7053 as core::ffi::c_int as WORD16,
            0x7083 as core::ffi::c_int as WORD16,
            0x70b3 as core::ffi::c_int as WORD16,
            0x70e3 as core::ffi::c_int as WORD16,
            0x7112 as core::ffi::c_int as WORD16,
            0x7141 as core::ffi::c_int as WORD16,
            0x7170 as core::ffi::c_int as WORD16,
            0x719e as core::ffi::c_int as WORD16,
            0x71cc as core::ffi::c_int as WORD16,
            0x71fa as core::ffi::c_int as WORD16,
            0x7228 as core::ffi::c_int as WORD16,
            0x7255 as core::ffi::c_int as WORD16,
            0x7282 as core::ffi::c_int as WORD16,
            0x72af as core::ffi::c_int as WORD16,
            0x72dc as core::ffi::c_int as WORD16,
            0x7308 as core::ffi::c_int as WORD16,
            0x7334 as core::ffi::c_int as WORD16,
            0x735f as core::ffi::c_int as WORD16,
            0x738b as core::ffi::c_int as WORD16,
            0x73b6 as core::ffi::c_int as WORD16,
            0x73e1 as core::ffi::c_int as WORD16,
            0x740b as core::ffi::c_int as WORD16,
            0x7436 as core::ffi::c_int as WORD16,
            0x7460 as core::ffi::c_int as WORD16,
            0x7489 as core::ffi::c_int as WORD16,
            0x74b3 as core::ffi::c_int as WORD16,
            0x74dc as core::ffi::c_int as WORD16,
            0x7505 as core::ffi::c_int as WORD16,
            0x752d as core::ffi::c_int as WORD16,
            0x7556 as core::ffi::c_int as WORD16,
            0x757e as core::ffi::c_int as WORD16,
            0x75a6 as core::ffi::c_int as WORD16,
            0x75cd as core::ffi::c_int as WORD16,
            0x75f4 as core::ffi::c_int as WORD16,
            0x761b as core::ffi::c_int as WORD16,
            0x7642 as core::ffi::c_int as WORD16,
            0x7668 as core::ffi::c_int as WORD16,
            0x768e as core::ffi::c_int as WORD16,
            0x76b4 as core::ffi::c_int as WORD16,
            0x76d9 as core::ffi::c_int as WORD16,
            0x76fe as core::ffi::c_int as WORD16,
            0x7723 as core::ffi::c_int as WORD16,
            0x7748 as core::ffi::c_int as WORD16,
            0x776c as core::ffi::c_int as WORD16,
            0x7790 as core::ffi::c_int as WORD16,
            0x77b4 as core::ffi::c_int as WORD16,
            0x77d8 as core::ffi::c_int as WORD16,
            0x77fb as core::ffi::c_int as WORD16,
            0x781e as core::ffi::c_int as WORD16,
            0x7840 as core::ffi::c_int as WORD16,
            0x7863 as core::ffi::c_int as WORD16,
            0x7885 as core::ffi::c_int as WORD16,
            0x78a6 as core::ffi::c_int as WORD16,
            0x78c8 as core::ffi::c_int as WORD16,
            0x78e9 as core::ffi::c_int as WORD16,
            0x790a as core::ffi::c_int as WORD16,
            0x792a as core::ffi::c_int as WORD16,
            0x794a as core::ffi::c_int as WORD16,
            0x796a as core::ffi::c_int as WORD16,
            0x798a as core::ffi::c_int as WORD16,
            0x79aa as core::ffi::c_int as WORD16,
            0x79c9 as core::ffi::c_int as WORD16,
            0x79e7 as core::ffi::c_int as WORD16,
            0x7a06 as core::ffi::c_int as WORD16,
            0x7a24 as core::ffi::c_int as WORD16,
            0x7a42 as core::ffi::c_int as WORD16,
            0x7a60 as core::ffi::c_int as WORD16,
            0x7a7d as core::ffi::c_int as WORD16,
            0x7a9a as core::ffi::c_int as WORD16,
            0x7ab7 as core::ffi::c_int as WORD16,
            0x7ad3 as core::ffi::c_int as WORD16,
            0x7aef as core::ffi::c_int as WORD16,
            0x7b0b as core::ffi::c_int as WORD16,
            0x7b27 as core::ffi::c_int as WORD16,
            0x7b42 as core::ffi::c_int as WORD16,
            0x7b5d as core::ffi::c_int as WORD16,
            0x7b78 as core::ffi::c_int as WORD16,
            0x7b92 as core::ffi::c_int as WORD16,
            0x7bac as core::ffi::c_int as WORD16,
            0x7bc6 as core::ffi::c_int as WORD16,
            0x7bdf as core::ffi::c_int as WORD16,
            0x7bf9 as core::ffi::c_int as WORD16,
            0x7c11 as core::ffi::c_int as WORD16,
            0x7c2a as core::ffi::c_int as WORD16,
            0x7c42 as core::ffi::c_int as WORD16,
            0x7c5a as core::ffi::c_int as WORD16,
            0x7c72 as core::ffi::c_int as WORD16,
            0x7c89 as core::ffi::c_int as WORD16,
            0x7ca0 as core::ffi::c_int as WORD16,
            0x7cb7 as core::ffi::c_int as WORD16,
            0x7cce as core::ffi::c_int as WORD16,
            0x7ce4 as core::ffi::c_int as WORD16,
            0x7cfa as core::ffi::c_int as WORD16,
            0x7d0f as core::ffi::c_int as WORD16,
            0x7d25 as core::ffi::c_int as WORD16,
            0x7d3a as core::ffi::c_int as WORD16,
            0x7d4e as core::ffi::c_int as WORD16,
            0x7d63 as core::ffi::c_int as WORD16,
            0x7d77 as core::ffi::c_int as WORD16,
            0x7d8a as core::ffi::c_int as WORD16,
            0x7d9e as core::ffi::c_int as WORD16,
            0x7db1 as core::ffi::c_int as WORD16,
            0x7dc4 as core::ffi::c_int as WORD16,
            0x7dd6 as core::ffi::c_int as WORD16,
            0x7de9 as core::ffi::c_int as WORD16,
            0x7dfb as core::ffi::c_int as WORD16,
            0x7e0c as core::ffi::c_int as WORD16,
            0x7e1e as core::ffi::c_int as WORD16,
            0x7e2f as core::ffi::c_int as WORD16,
            0x7e3f as core::ffi::c_int as WORD16,
            0x7e50 as core::ffi::c_int as WORD16,
            0x7e60 as core::ffi::c_int as WORD16,
            0x7e70 as core::ffi::c_int as WORD16,
            0x7e7f as core::ffi::c_int as WORD16,
            0x7e8e as core::ffi::c_int as WORD16,
            0x7e9d as core::ffi::c_int as WORD16,
            0x7eac as core::ffi::c_int as WORD16,
            0x7eba as core::ffi::c_int as WORD16,
            0x7ec8 as core::ffi::c_int as WORD16,
            0x7ed6 as core::ffi::c_int as WORD16,
            0x7ee3 as core::ffi::c_int as WORD16,
            0x7ef0 as core::ffi::c_int as WORD16,
            0x7efd as core::ffi::c_int as WORD16,
            0x7f0a as core::ffi::c_int as WORD16,
            0x7f16 as core::ffi::c_int as WORD16,
            0x7f22 as core::ffi::c_int as WORD16,
            0x7f2d as core::ffi::c_int as WORD16,
            0x7f38 as core::ffi::c_int as WORD16,
            0x7f43 as core::ffi::c_int as WORD16,
            0x7f4e as core::ffi::c_int as WORD16,
            0x7f58 as core::ffi::c_int as WORD16,
            0x7f62 as core::ffi::c_int as WORD16,
            0x7f6c as core::ffi::c_int as WORD16,
            0x7f75 as core::ffi::c_int as WORD16,
            0x7f7e as core::ffi::c_int as WORD16,
            0x7f87 as core::ffi::c_int as WORD16,
            0x7f90 as core::ffi::c_int as WORD16,
            0x7f98 as core::ffi::c_int as WORD16,
            0x7fa0 as core::ffi::c_int as WORD16,
            0x7fa7 as core::ffi::c_int as WORD16,
            0x7fae as core::ffi::c_int as WORD16,
            0x7fb5 as core::ffi::c_int as WORD16,
            0x7fbc as core::ffi::c_int as WORD16,
            0x7fc2 as core::ffi::c_int as WORD16,
            0x7fc8 as core::ffi::c_int as WORD16,
            0x7fce as core::ffi::c_int as WORD16,
            0x7fd3 as core::ffi::c_int as WORD16,
            0x7fd9 as core::ffi::c_int as WORD16,
            0x7fdd as core::ffi::c_int as WORD16,
            0x7fe2 as core::ffi::c_int as WORD16,
            0x7fe6 as core::ffi::c_int as WORD16,
            0x7fea as core::ffi::c_int as WORD16,
            0x7fed as core::ffi::c_int as WORD16,
            0x7ff1 as core::ffi::c_int as WORD16,
            0x7ff4 as core::ffi::c_int as WORD16,
            0x7ff6 as core::ffi::c_int as WORD16,
            0x7ff8 as core::ffi::c_int as WORD16,
            0x7ffa as core::ffi::c_int as WORD16,
            0x7ffc as core::ffi::c_int as WORD16,
            0x7ffe as core::ffi::c_int as WORD16,
            0x7fff as core::ffi::c_int as WORD16,
            0x7fff as core::ffi::c_int as WORD16,
            0x7fff as core::ffi::c_int as WORD16,
            0x7fff as core::ffi::c_int as WORD16,
        ],
        sine_table8_16: [
            -(0 as core::ffi::c_int) as WORD16,
            -(0x18f9 as core::ffi::c_int) as WORD16,
            -(0x30fc as core::ffi::c_int) as WORD16,
            -(0x471d as core::ffi::c_int) as WORD16,
            -(0x5a82 as core::ffi::c_int) as WORD16,
            -(0x6a6e as core::ffi::c_int) as WORD16,
            -(0x7642 as core::ffi::c_int) as WORD16,
            -(0x7d8a as core::ffi::c_int) as WORD16,
        ],
        log_dual_is_table: [
            -(0x8000 as core::ffi::c_int) as WORD16,
            0 as core::ffi::c_int as WORD16,
            0x1000 as core::ffi::c_int as WORD16,
            0x195c as core::ffi::c_int as WORD16,
            0x2000 as core::ffi::c_int as WORD16,
            0x2527 as core::ffi::c_int as WORD16,
            0x295c as core::ffi::c_int as WORD16,
            0x2ceb as core::ffi::c_int as WORD16,
            0x3000 as core::ffi::c_int as WORD16,
            0x32b8 as core::ffi::c_int as WORD16,
            0x3527 as core::ffi::c_int as WORD16,
            0x375a as core::ffi::c_int as WORD16,
            0x395c as core::ffi::c_int as WORD16,
            0x3b35 as core::ffi::c_int as WORD16,
            0x3ceb as core::ffi::c_int as WORD16,
            0x3e83 as core::ffi::c_int as WORD16,
            0x4000 as core::ffi::c_int as WORD16,
            0x4166 as core::ffi::c_int as WORD16,
            0x42b8 as core::ffi::c_int as WORD16,
            0x43f8 as core::ffi::c_int as WORD16,
            0x4527 as core::ffi::c_int as WORD16,
            0x4647 as core::ffi::c_int as WORD16,
            0x475a as core::ffi::c_int as WORD16,
            0x4861 as core::ffi::c_int as WORD16,
            0x495c as core::ffi::c_int as WORD16,
            0x4a4d as core::ffi::c_int as WORD16,
            0x4b35 as core::ffi::c_int as WORD16,
            0x4c14 as core::ffi::c_int as WORD16,
            0x4ceb as core::ffi::c_int as WORD16,
            0x4dba as core::ffi::c_int as WORD16,
            0x4e83 as core::ffi::c_int as WORD16,
            0x4f44 as core::ffi::c_int as WORD16,
            0x5000 as core::ffi::c_int as WORD16,
            0x50b6 as core::ffi::c_int as WORD16,
            0x5166 as core::ffi::c_int as WORD16,
            0x5212 as core::ffi::c_int as WORD16,
            0x52b8 as core::ffi::c_int as WORD16,
            0x535a as core::ffi::c_int as WORD16,
            0x53f8 as core::ffi::c_int as WORD16,
            0x5491 as core::ffi::c_int as WORD16,
            0x5527 as core::ffi::c_int as WORD16,
            0x55b9 as core::ffi::c_int as WORD16,
            0x5647 as core::ffi::c_int as WORD16,
            0x56d2 as core::ffi::c_int as WORD16,
            0x575a as core::ffi::c_int as WORD16,
            0x57df as core::ffi::c_int as WORD16,
            0x5861 as core::ffi::c_int as WORD16,
            0x58e0 as core::ffi::c_int as WORD16,
            0x595c as core::ffi::c_int as WORD16,
            0x59d6 as core::ffi::c_int as WORD16,
            0x5a4d as core::ffi::c_int as WORD16,
            0x5ac2 as core::ffi::c_int as WORD16,
            0x5b35 as core::ffi::c_int as WORD16,
            0x5ba6 as core::ffi::c_int as WORD16,
            0x5c14 as core::ffi::c_int as WORD16,
            0x5c80 as core::ffi::c_int as WORD16,
            0x5ceb as core::ffi::c_int as WORD16,
            0x5d54 as core::ffi::c_int as WORD16,
            0x5dba as core::ffi::c_int as WORD16,
            0x5e1f as core::ffi::c_int as WORD16,
            0x5e83 as core::ffi::c_int as WORD16,
            0x5ee4 as core::ffi::c_int as WORD16,
            0x5f44 as core::ffi::c_int as WORD16,
            0x5fa3 as core::ffi::c_int as WORD16,
            0x6000 as core::ffi::c_int as WORD16,
        ],
        down_mix_martix: [
            [
                [
                    405185594 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    315041546 as core::ffi::c_int,
                    315041546 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                ],
                [
                    0 as core::ffi::c_int,
                    405185594 as core::ffi::c_int,
                    315041546 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    315041546 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                ],
            ],
            [
                [
                    405185594 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    286509481 as core::ffi::c_int,
                    95503160 as core::ffi::c_int,
                    286509481 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                ],
                [
                    0 as core::ffi::c_int,
                    405185594 as core::ffi::c_int,
                    286509481 as core::ffi::c_int,
                    95503160 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    286509481 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                ],
            ],
            [
                [
                    405185594 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    244131873 as core::ffi::c_int,
                    244131873 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    244131873 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                ],
                [
                    0 as core::ffi::c_int,
                    405185594 as core::ffi::c_int,
                    244131873 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    244131873 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    244131873 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                ],
            ],
            [
                [
                    405185594 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    226641828 as core::ffi::c_int,
                    75547276 as core::ffi::c_int,
                    226641828 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    226641828 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                ],
                [
                    0 as core::ffi::c_int,
                    405185594 as core::ffi::c_int,
                    75547276 as core::ffi::c_int,
                    226641828 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    226641828 as core::ffi::c_int,
                    0 as core::ffi::c_int,
                    226641828 as core::ffi::c_int,
                ],
            ],
        ],
        cc_gain_scale: [
            585461881 as core::ffi::c_int,
            638450708 as core::ffi::c_int,
            759250125 as core::ffi::c_int,
            1073741824 as core::ffi::c_int,
        ],
        inv_table: [
            0x7f80 as core::ffi::c_int as WORD16,
            0x7f02 as core::ffi::c_int as WORD16,
            0x7e84 as core::ffi::c_int as WORD16,
            0x7e08 as core::ffi::c_int as WORD16,
            0x7d8c as core::ffi::c_int as WORD16,
            0x7d12 as core::ffi::c_int as WORD16,
            0x7c98 as core::ffi::c_int as WORD16,
            0x7c1f as core::ffi::c_int as WORD16,
            0x7ba7 as core::ffi::c_int as WORD16,
            0x7b30 as core::ffi::c_int as WORD16,
            0x7aba as core::ffi::c_int as WORD16,
            0x7a45 as core::ffi::c_int as WORD16,
            0x79d0 as core::ffi::c_int as WORD16,
            0x795d as core::ffi::c_int as WORD16,
            0x78ea as core::ffi::c_int as WORD16,
            0x7878 as core::ffi::c_int as WORD16,
            0x7808 as core::ffi::c_int as WORD16,
            0x7797 as core::ffi::c_int as WORD16,
            0x7728 as core::ffi::c_int as WORD16,
            0x76ba as core::ffi::c_int as WORD16,
            0x764c as core::ffi::c_int as WORD16,
            0x75df as core::ffi::c_int as WORD16,
            0x7573 as core::ffi::c_int as WORD16,
            0x7507 as core::ffi::c_int as WORD16,
            0x749d as core::ffi::c_int as WORD16,
            0x7433 as core::ffi::c_int as WORD16,
            0x73ca as core::ffi::c_int as WORD16,
            0x7361 as core::ffi::c_int as WORD16,
            0x72fa as core::ffi::c_int as WORD16,
            0x7293 as core::ffi::c_int as WORD16,
            0x722d as core::ffi::c_int as WORD16,
            0x71c7 as core::ffi::c_int as WORD16,
            0x7162 as core::ffi::c_int as WORD16,
            0x70fe as core::ffi::c_int as WORD16,
            0x709b as core::ffi::c_int as WORD16,
            0x7038 as core::ffi::c_int as WORD16,
            0x6fd6 as core::ffi::c_int as WORD16,
            0x6f75 as core::ffi::c_int as WORD16,
            0x6f14 as core::ffi::c_int as WORD16,
            0x6eb4 as core::ffi::c_int as WORD16,
            0x6e54 as core::ffi::c_int as WORD16,
            0x6df6 as core::ffi::c_int as WORD16,
            0x6d98 as core::ffi::c_int as WORD16,
            0x6d3a as core::ffi::c_int as WORD16,
            0x6cdd as core::ffi::c_int as WORD16,
            0x6c81 as core::ffi::c_int as WORD16,
            0x6c25 as core::ffi::c_int as WORD16,
            0x6bca as core::ffi::c_int as WORD16,
            0x6b70 as core::ffi::c_int as WORD16,
            0x6b16 as core::ffi::c_int as WORD16,
            0x6abc as core::ffi::c_int as WORD16,
            0x6a64 as core::ffi::c_int as WORD16,
            0x6a0c as core::ffi::c_int as WORD16,
            0x69b4 as core::ffi::c_int as WORD16,
            0x695d as core::ffi::c_int as WORD16,
            0x6907 as core::ffi::c_int as WORD16,
            0x68b1 as core::ffi::c_int as WORD16,
            0x685b as core::ffi::c_int as WORD16,
            0x6807 as core::ffi::c_int as WORD16,
            0x67b2 as core::ffi::c_int as WORD16,
            0x675e as core::ffi::c_int as WORD16,
            0x670b as core::ffi::c_int as WORD16,
            0x66b9 as core::ffi::c_int as WORD16,
            0x6666 as core::ffi::c_int as WORD16,
            0x6615 as core::ffi::c_int as WORD16,
            0x65c4 as core::ffi::c_int as WORD16,
            0x6573 as core::ffi::c_int as WORD16,
            0x6523 as core::ffi::c_int as WORD16,
            0x64d3 as core::ffi::c_int as WORD16,
            0x6484 as core::ffi::c_int as WORD16,
            0x6435 as core::ffi::c_int as WORD16,
            0x63e7 as core::ffi::c_int as WORD16,
            0x6399 as core::ffi::c_int as WORD16,
            0x634c as core::ffi::c_int as WORD16,
            0x62ff as core::ffi::c_int as WORD16,
            0x62b3 as core::ffi::c_int as WORD16,
            0x6267 as core::ffi::c_int as WORD16,
            0x621c as core::ffi::c_int as WORD16,
            0x61d1 as core::ffi::c_int as WORD16,
            0x6186 as core::ffi::c_int as WORD16,
            0x613c as core::ffi::c_int as WORD16,
            0x60f2 as core::ffi::c_int as WORD16,
            0x60a9 as core::ffi::c_int as WORD16,
            0x6060 as core::ffi::c_int as WORD16,
            0x6018 as core::ffi::c_int as WORD16,
            0x5fd0 as core::ffi::c_int as WORD16,
            0x5f89 as core::ffi::c_int as WORD16,
            0x5f41 as core::ffi::c_int as WORD16,
            0x5efb as core::ffi::c_int as WORD16,
            0x5eb5 as core::ffi::c_int as WORD16,
            0x5e6f as core::ffi::c_int as WORD16,
            0x5e29 as core::ffi::c_int as WORD16,
            0x5de4 as core::ffi::c_int as WORD16,
            0x5d9f as core::ffi::c_int as WORD16,
            0x5d5b as core::ffi::c_int as WORD16,
            0x5d17 as core::ffi::c_int as WORD16,
            0x5cd4 as core::ffi::c_int as WORD16,
            0x5c91 as core::ffi::c_int as WORD16,
            0x5c4e as core::ffi::c_int as WORD16,
            0x5c0c as core::ffi::c_int as WORD16,
            0x5bca as core::ffi::c_int as WORD16,
            0x5b88 as core::ffi::c_int as WORD16,
            0x5b47 as core::ffi::c_int as WORD16,
            0x5b06 as core::ffi::c_int as WORD16,
            0x5ac5 as core::ffi::c_int as WORD16,
            0x5a85 as core::ffi::c_int as WORD16,
            0x5a45 as core::ffi::c_int as WORD16,
            0x5a06 as core::ffi::c_int as WORD16,
            0x59c6 as core::ffi::c_int as WORD16,
            0x5988 as core::ffi::c_int as WORD16,
            0x5949 as core::ffi::c_int as WORD16,
            0x590b as core::ffi::c_int as WORD16,
            0x58cd as core::ffi::c_int as WORD16,
            0x5890 as core::ffi::c_int as WORD16,
            0x5853 as core::ffi::c_int as WORD16,
            0x5816 as core::ffi::c_int as WORD16,
            0x57da as core::ffi::c_int as WORD16,
            0x579d as core::ffi::c_int as WORD16,
            0x5762 as core::ffi::c_int as WORD16,
            0x5726 as core::ffi::c_int as WORD16,
            0x56eb as core::ffi::c_int as WORD16,
            0x56b0 as core::ffi::c_int as WORD16,
            0x5676 as core::ffi::c_int as WORD16,
            0x563b as core::ffi::c_int as WORD16,
            0x5601 as core::ffi::c_int as WORD16,
            0x55c8 as core::ffi::c_int as WORD16,
            0x558e as core::ffi::c_int as WORD16,
            0x5555 as core::ffi::c_int as WORD16,
            0x551d as core::ffi::c_int as WORD16,
            0x54e4 as core::ffi::c_int as WORD16,
            0x54ac as core::ffi::c_int as WORD16,
            0x5474 as core::ffi::c_int as WORD16,
            0x543d as core::ffi::c_int as WORD16,
            0x5405 as core::ffi::c_int as WORD16,
            0x53ce as core::ffi::c_int as WORD16,
            0x5398 as core::ffi::c_int as WORD16,
            0x5361 as core::ffi::c_int as WORD16,
            0x532b as core::ffi::c_int as WORD16,
            0x52f5 as core::ffi::c_int as WORD16,
            0x52bf as core::ffi::c_int as WORD16,
            0x528a as core::ffi::c_int as WORD16,
            0x5255 as core::ffi::c_int as WORD16,
            0x5220 as core::ffi::c_int as WORD16,
            0x51ec as core::ffi::c_int as WORD16,
            0x51b7 as core::ffi::c_int as WORD16,
            0x5183 as core::ffi::c_int as WORD16,
            0x514f as core::ffi::c_int as WORD16,
            0x511c as core::ffi::c_int as WORD16,
            0x50e9 as core::ffi::c_int as WORD16,
            0x50b6 as core::ffi::c_int as WORD16,
            0x5083 as core::ffi::c_int as WORD16,
            0x5050 as core::ffi::c_int as WORD16,
            0x501e as core::ffi::c_int as WORD16,
            0x4fec as core::ffi::c_int as WORD16,
            0x4fba as core::ffi::c_int as WORD16,
            0x4f89 as core::ffi::c_int as WORD16,
            0x4f57 as core::ffi::c_int as WORD16,
            0x4f26 as core::ffi::c_int as WORD16,
            0x4ef6 as core::ffi::c_int as WORD16,
            0x4ec5 as core::ffi::c_int as WORD16,
            0x4e95 as core::ffi::c_int as WORD16,
            0x4e64 as core::ffi::c_int as WORD16,
            0x4e35 as core::ffi::c_int as WORD16,
            0x4e05 as core::ffi::c_int as WORD16,
            0x4dd5 as core::ffi::c_int as WORD16,
            0x4da6 as core::ffi::c_int as WORD16,
            0x4d77 as core::ffi::c_int as WORD16,
            0x4d48 as core::ffi::c_int as WORD16,
            0x4d1a as core::ffi::c_int as WORD16,
            0x4cec as core::ffi::c_int as WORD16,
            0x4cbd as core::ffi::c_int as WORD16,
            0x4c90 as core::ffi::c_int as WORD16,
            0x4c62 as core::ffi::c_int as WORD16,
            0x4c34 as core::ffi::c_int as WORD16,
            0x4c07 as core::ffi::c_int as WORD16,
            0x4bda as core::ffi::c_int as WORD16,
            0x4bad as core::ffi::c_int as WORD16,
            0x4b81 as core::ffi::c_int as WORD16,
            0x4b54 as core::ffi::c_int as WORD16,
            0x4b28 as core::ffi::c_int as WORD16,
            0x4afc as core::ffi::c_int as WORD16,
            0x4ad0 as core::ffi::c_int as WORD16,
            0x4aa4 as core::ffi::c_int as WORD16,
            0x4a79 as core::ffi::c_int as WORD16,
            0x4a4e as core::ffi::c_int as WORD16,
            0x4a23 as core::ffi::c_int as WORD16,
            0x49f8 as core::ffi::c_int as WORD16,
            0x49cd as core::ffi::c_int as WORD16,
            0x49a3 as core::ffi::c_int as WORD16,
            0x4979 as core::ffi::c_int as WORD16,
            0x494e as core::ffi::c_int as WORD16,
            0x4925 as core::ffi::c_int as WORD16,
            0x48fb as core::ffi::c_int as WORD16,
            0x48d1 as core::ffi::c_int as WORD16,
            0x48a8 as core::ffi::c_int as WORD16,
            0x487f as core::ffi::c_int as WORD16,
            0x4856 as core::ffi::c_int as WORD16,
            0x482d as core::ffi::c_int as WORD16,
            0x4805 as core::ffi::c_int as WORD16,
            0x47dc as core::ffi::c_int as WORD16,
            0x47b4 as core::ffi::c_int as WORD16,
            0x478c as core::ffi::c_int as WORD16,
            0x4764 as core::ffi::c_int as WORD16,
            0x473c as core::ffi::c_int as WORD16,
            0x4715 as core::ffi::c_int as WORD16,
            0x46ed as core::ffi::c_int as WORD16,
            0x46c6 as core::ffi::c_int as WORD16,
            0x469f as core::ffi::c_int as WORD16,
            0x4678 as core::ffi::c_int as WORD16,
            0x4651 as core::ffi::c_int as WORD16,
            0x462b as core::ffi::c_int as WORD16,
            0x4604 as core::ffi::c_int as WORD16,
            0x45de as core::ffi::c_int as WORD16,
            0x45b8 as core::ffi::c_int as WORD16,
            0x4592 as core::ffi::c_int as WORD16,
            0x456c as core::ffi::c_int as WORD16,
            0x4547 as core::ffi::c_int as WORD16,
            0x4521 as core::ffi::c_int as WORD16,
            0x44fc as core::ffi::c_int as WORD16,
            0x44d7 as core::ffi::c_int as WORD16,
            0x44b2 as core::ffi::c_int as WORD16,
            0x448d as core::ffi::c_int as WORD16,
            0x4469 as core::ffi::c_int as WORD16,
            0x4444 as core::ffi::c_int as WORD16,
            0x4420 as core::ffi::c_int as WORD16,
            0x43fc as core::ffi::c_int as WORD16,
            0x43d8 as core::ffi::c_int as WORD16,
            0x43b4 as core::ffi::c_int as WORD16,
            0x4390 as core::ffi::c_int as WORD16,
            0x436d as core::ffi::c_int as WORD16,
            0x4349 as core::ffi::c_int as WORD16,
            0x4326 as core::ffi::c_int as WORD16,
            0x4303 as core::ffi::c_int as WORD16,
            0x42e0 as core::ffi::c_int as WORD16,
            0x42bd as core::ffi::c_int as WORD16,
            0x429a as core::ffi::c_int as WORD16,
            0x4277 as core::ffi::c_int as WORD16,
            0x4255 as core::ffi::c_int as WORD16,
            0x4233 as core::ffi::c_int as WORD16,
            0x4211 as core::ffi::c_int as WORD16,
            0x41ee as core::ffi::c_int as WORD16,
            0x41cd as core::ffi::c_int as WORD16,
            0x41ab as core::ffi::c_int as WORD16,
            0x4189 as core::ffi::c_int as WORD16,
            0x4168 as core::ffi::c_int as WORD16,
            0x4146 as core::ffi::c_int as WORD16,
            0x4125 as core::ffi::c_int as WORD16,
            0x4104 as core::ffi::c_int as WORD16,
            0x40e3 as core::ffi::c_int as WORD16,
            0x40c2 as core::ffi::c_int as WORD16,
            0x40a2 as core::ffi::c_int as WORD16,
            0x4081 as core::ffi::c_int as WORD16,
            0x4061 as core::ffi::c_int as WORD16,
            0x4040 as core::ffi::c_int as WORD16,
            0x4020 as core::ffi::c_int as WORD16,
            0x4000 as core::ffi::c_int as WORD16,
        ],
        sqrt_table: [
            0x5a82 as core::ffi::c_int as WORD16,
            0x5ab0 as core::ffi::c_int as WORD16,
            0x5add as core::ffi::c_int as WORD16,
            0x5b0a as core::ffi::c_int as WORD16,
            0x5b37 as core::ffi::c_int as WORD16,
            0x5b64 as core::ffi::c_int as WORD16,
            0x5b90 as core::ffi::c_int as WORD16,
            0x5bbd as core::ffi::c_int as WORD16,
            0x5bea as core::ffi::c_int as WORD16,
            0x5c16 as core::ffi::c_int as WORD16,
            0x5c43 as core::ffi::c_int as WORD16,
            0x5c6f as core::ffi::c_int as WORD16,
            0x5c9b as core::ffi::c_int as WORD16,
            0x5cc8 as core::ffi::c_int as WORD16,
            0x5cf4 as core::ffi::c_int as WORD16,
            0x5d20 as core::ffi::c_int as WORD16,
            0x5d4c as core::ffi::c_int as WORD16,
            0x5d77 as core::ffi::c_int as WORD16,
            0x5da3 as core::ffi::c_int as WORD16,
            0x5dcf as core::ffi::c_int as WORD16,
            0x5dfb as core::ffi::c_int as WORD16,
            0x5e26 as core::ffi::c_int as WORD16,
            0x5e52 as core::ffi::c_int as WORD16,
            0x5e7d as core::ffi::c_int as WORD16,
            0x5ea8 as core::ffi::c_int as WORD16,
            0x5ed3 as core::ffi::c_int as WORD16,
            0x5eff as core::ffi::c_int as WORD16,
            0x5f2a as core::ffi::c_int as WORD16,
            0x5f55 as core::ffi::c_int as WORD16,
            0x5f80 as core::ffi::c_int as WORD16,
            0x5fab as core::ffi::c_int as WORD16,
            0x5fd5 as core::ffi::c_int as WORD16,
            0x6000 as core::ffi::c_int as WORD16,
            0x602b as core::ffi::c_int as WORD16,
            0x6055 as core::ffi::c_int as WORD16,
            0x6080 as core::ffi::c_int as WORD16,
            0x60aa as core::ffi::c_int as WORD16,
            0x60d4 as core::ffi::c_int as WORD16,
            0x60ff as core::ffi::c_int as WORD16,
            0x6129 as core::ffi::c_int as WORD16,
            0x6153 as core::ffi::c_int as WORD16,
            0x617d as core::ffi::c_int as WORD16,
            0x61a7 as core::ffi::c_int as WORD16,
            0x61d1 as core::ffi::c_int as WORD16,
            0x61fb as core::ffi::c_int as WORD16,
            0x6225 as core::ffi::c_int as WORD16,
            0x624e as core::ffi::c_int as WORD16,
            0x6278 as core::ffi::c_int as WORD16,
            0x62a1 as core::ffi::c_int as WORD16,
            0x62cb as core::ffi::c_int as WORD16,
            0x62f4 as core::ffi::c_int as WORD16,
            0x631e as core::ffi::c_int as WORD16,
            0x6347 as core::ffi::c_int as WORD16,
            0x6370 as core::ffi::c_int as WORD16,
            0x6399 as core::ffi::c_int as WORD16,
            0x63c2 as core::ffi::c_int as WORD16,
            0x63ec as core::ffi::c_int as WORD16,
            0x6414 as core::ffi::c_int as WORD16,
            0x643d as core::ffi::c_int as WORD16,
            0x6466 as core::ffi::c_int as WORD16,
            0x648f as core::ffi::c_int as WORD16,
            0x64b8 as core::ffi::c_int as WORD16,
            0x64e0 as core::ffi::c_int as WORD16,
            0x6509 as core::ffi::c_int as WORD16,
            0x6531 as core::ffi::c_int as WORD16,
            0x655a as core::ffi::c_int as WORD16,
            0x6582 as core::ffi::c_int as WORD16,
            0x65ab as core::ffi::c_int as WORD16,
            0x65d3 as core::ffi::c_int as WORD16,
            0x65fb as core::ffi::c_int as WORD16,
            0x6623 as core::ffi::c_int as WORD16,
            0x664b as core::ffi::c_int as WORD16,
            0x6673 as core::ffi::c_int as WORD16,
            0x669b as core::ffi::c_int as WORD16,
            0x66c3 as core::ffi::c_int as WORD16,
            0x66eb as core::ffi::c_int as WORD16,
            0x6713 as core::ffi::c_int as WORD16,
            0x673a as core::ffi::c_int as WORD16,
            0x6762 as core::ffi::c_int as WORD16,
            0x678a as core::ffi::c_int as WORD16,
            0x67b1 as core::ffi::c_int as WORD16,
            0x67d9 as core::ffi::c_int as WORD16,
            0x6800 as core::ffi::c_int as WORD16,
            0x6827 as core::ffi::c_int as WORD16,
            0x684f as core::ffi::c_int as WORD16,
            0x6876 as core::ffi::c_int as WORD16,
            0x689d as core::ffi::c_int as WORD16,
            0x68c4 as core::ffi::c_int as WORD16,
            0x68eb as core::ffi::c_int as WORD16,
            0x6912 as core::ffi::c_int as WORD16,
            0x6939 as core::ffi::c_int as WORD16,
            0x6960 as core::ffi::c_int as WORD16,
            0x6987 as core::ffi::c_int as WORD16,
            0x69ae as core::ffi::c_int as WORD16,
            0x69d4 as core::ffi::c_int as WORD16,
            0x69fb as core::ffi::c_int as WORD16,
            0x6a22 as core::ffi::c_int as WORD16,
            0x6a48 as core::ffi::c_int as WORD16,
            0x6a6f as core::ffi::c_int as WORD16,
            0x6a95 as core::ffi::c_int as WORD16,
            0x6abc as core::ffi::c_int as WORD16,
            0x6ae2 as core::ffi::c_int as WORD16,
            0x6b08 as core::ffi::c_int as WORD16,
            0x6b2f as core::ffi::c_int as WORD16,
            0x6b55 as core::ffi::c_int as WORD16,
            0x6b7b as core::ffi::c_int as WORD16,
            0x6ba1 as core::ffi::c_int as WORD16,
            0x6bc7 as core::ffi::c_int as WORD16,
            0x6bed as core::ffi::c_int as WORD16,
            0x6c13 as core::ffi::c_int as WORD16,
            0x6c39 as core::ffi::c_int as WORD16,
            0x6c5f as core::ffi::c_int as WORD16,
            0x6c84 as core::ffi::c_int as WORD16,
            0x6caa as core::ffi::c_int as WORD16,
            0x6cd0 as core::ffi::c_int as WORD16,
            0x6cf5 as core::ffi::c_int as WORD16,
            0x6d1b as core::ffi::c_int as WORD16,
            0x6d41 as core::ffi::c_int as WORD16,
            0x6d66 as core::ffi::c_int as WORD16,
            0x6d8b as core::ffi::c_int as WORD16,
            0x6db1 as core::ffi::c_int as WORD16,
            0x6dd6 as core::ffi::c_int as WORD16,
            0x6dfb as core::ffi::c_int as WORD16,
            0x6e21 as core::ffi::c_int as WORD16,
            0x6e46 as core::ffi::c_int as WORD16,
            0x6e6b as core::ffi::c_int as WORD16,
            0x6e90 as core::ffi::c_int as WORD16,
            0x6eb5 as core::ffi::c_int as WORD16,
            0x6eda as core::ffi::c_int as WORD16,
            0x6eff as core::ffi::c_int as WORD16,
            0x6f24 as core::ffi::c_int as WORD16,
            0x6f49 as core::ffi::c_int as WORD16,
            0x6f6d as core::ffi::c_int as WORD16,
            0x6f92 as core::ffi::c_int as WORD16,
            0x6fb7 as core::ffi::c_int as WORD16,
            0x6fdb as core::ffi::c_int as WORD16,
            0x7000 as core::ffi::c_int as WORD16,
            0x7025 as core::ffi::c_int as WORD16,
            0x7049 as core::ffi::c_int as WORD16,
            0x706e as core::ffi::c_int as WORD16,
            0x7092 as core::ffi::c_int as WORD16,
            0x70b6 as core::ffi::c_int as WORD16,
            0x70db as core::ffi::c_int as WORD16,
            0x70ff as core::ffi::c_int as WORD16,
            0x7123 as core::ffi::c_int as WORD16,
            0x7147 as core::ffi::c_int as WORD16,
            0x716b as core::ffi::c_int as WORD16,
            0x7190 as core::ffi::c_int as WORD16,
            0x71b4 as core::ffi::c_int as WORD16,
            0x71d8 as core::ffi::c_int as WORD16,
            0x71fc as core::ffi::c_int as WORD16,
            0x721f as core::ffi::c_int as WORD16,
            0x7243 as core::ffi::c_int as WORD16,
            0x7267 as core::ffi::c_int as WORD16,
            0x728b as core::ffi::c_int as WORD16,
            0x72af as core::ffi::c_int as WORD16,
            0x72d2 as core::ffi::c_int as WORD16,
            0x72f6 as core::ffi::c_int as WORD16,
            0x731a as core::ffi::c_int as WORD16,
            0x733d as core::ffi::c_int as WORD16,
            0x7361 as core::ffi::c_int as WORD16,
            0x7384 as core::ffi::c_int as WORD16,
            0x73a8 as core::ffi::c_int as WORD16,
            0x73cb as core::ffi::c_int as WORD16,
            0x73ee as core::ffi::c_int as WORD16,
            0x7412 as core::ffi::c_int as WORD16,
            0x7435 as core::ffi::c_int as WORD16,
            0x7458 as core::ffi::c_int as WORD16,
            0x747b as core::ffi::c_int as WORD16,
            0x749e as core::ffi::c_int as WORD16,
            0x74c2 as core::ffi::c_int as WORD16,
            0x74e5 as core::ffi::c_int as WORD16,
            0x7508 as core::ffi::c_int as WORD16,
            0x752b as core::ffi::c_int as WORD16,
            0x754e as core::ffi::c_int as WORD16,
            0x7570 as core::ffi::c_int as WORD16,
            0x7593 as core::ffi::c_int as WORD16,
            0x75b6 as core::ffi::c_int as WORD16,
            0x75d9 as core::ffi::c_int as WORD16,
            0x75fc as core::ffi::c_int as WORD16,
            0x761e as core::ffi::c_int as WORD16,
            0x7641 as core::ffi::c_int as WORD16,
            0x7664 as core::ffi::c_int as WORD16,
            0x7686 as core::ffi::c_int as WORD16,
            0x76a9 as core::ffi::c_int as WORD16,
            0x76cb as core::ffi::c_int as WORD16,
            0x76ee as core::ffi::c_int as WORD16,
            0x7710 as core::ffi::c_int as WORD16,
            0x7733 as core::ffi::c_int as WORD16,
            0x7755 as core::ffi::c_int as WORD16,
            0x7777 as core::ffi::c_int as WORD16,
            0x7799 as core::ffi::c_int as WORD16,
            0x77bc as core::ffi::c_int as WORD16,
            0x77de as core::ffi::c_int as WORD16,
            0x7800 as core::ffi::c_int as WORD16,
            0x7822 as core::ffi::c_int as WORD16,
            0x7844 as core::ffi::c_int as WORD16,
            0x7866 as core::ffi::c_int as WORD16,
            0x7888 as core::ffi::c_int as WORD16,
            0x78aa as core::ffi::c_int as WORD16,
            0x78cc as core::ffi::c_int as WORD16,
            0x78ee as core::ffi::c_int as WORD16,
            0x7910 as core::ffi::c_int as WORD16,
            0x7932 as core::ffi::c_int as WORD16,
            0x7953 as core::ffi::c_int as WORD16,
            0x7975 as core::ffi::c_int as WORD16,
            0x7997 as core::ffi::c_int as WORD16,
            0x79b9 as core::ffi::c_int as WORD16,
            0x79da as core::ffi::c_int as WORD16,
            0x79fc as core::ffi::c_int as WORD16,
            0x7a1d as core::ffi::c_int as WORD16,
            0x7a3f as core::ffi::c_int as WORD16,
            0x7a60 as core::ffi::c_int as WORD16,
            0x7a82 as core::ffi::c_int as WORD16,
            0x7aa3 as core::ffi::c_int as WORD16,
            0x7ac5 as core::ffi::c_int as WORD16,
            0x7ae6 as core::ffi::c_int as WORD16,
            0x7b07 as core::ffi::c_int as WORD16,
            0x7b29 as core::ffi::c_int as WORD16,
            0x7b4a as core::ffi::c_int as WORD16,
            0x7b6b as core::ffi::c_int as WORD16,
            0x7b8c as core::ffi::c_int as WORD16,
            0x7bad as core::ffi::c_int as WORD16,
            0x7bce as core::ffi::c_int as WORD16,
            0x7bef as core::ffi::c_int as WORD16,
            0x7c11 as core::ffi::c_int as WORD16,
            0x7c32 as core::ffi::c_int as WORD16,
            0x7c52 as core::ffi::c_int as WORD16,
            0x7c73 as core::ffi::c_int as WORD16,
            0x7c94 as core::ffi::c_int as WORD16,
            0x7cb5 as core::ffi::c_int as WORD16,
            0x7cd6 as core::ffi::c_int as WORD16,
            0x7cf7 as core::ffi::c_int as WORD16,
            0x7d18 as core::ffi::c_int as WORD16,
            0x7d38 as core::ffi::c_int as WORD16,
            0x7d59 as core::ffi::c_int as WORD16,
            0x7d7a as core::ffi::c_int as WORD16,
            0x7d9a as core::ffi::c_int as WORD16,
            0x7dbb as core::ffi::c_int as WORD16,
            0x7ddb as core::ffi::c_int as WORD16,
            0x7dfc as core::ffi::c_int as WORD16,
            0x7e1c as core::ffi::c_int as WORD16,
            0x7e3d as core::ffi::c_int as WORD16,
            0x7e5d as core::ffi::c_int as WORD16,
            0x7e7e as core::ffi::c_int as WORD16,
            0x7e9e as core::ffi::c_int as WORD16,
            0x7ebe as core::ffi::c_int as WORD16,
            0x7edf as core::ffi::c_int as WORD16,
            0x7eff as core::ffi::c_int as WORD16,
            0x7f1f as core::ffi::c_int as WORD16,
            0x7f3f as core::ffi::c_int as WORD16,
            0x7f60 as core::ffi::c_int as WORD16,
            0x7f80 as core::ffi::c_int as WORD16,
            0x7fa0 as core::ffi::c_int as WORD16,
            0x7fc0 as core::ffi::c_int as WORD16,
            0x7fe0 as core::ffi::c_int as WORD16,
            0x7fff as core::ffi::c_int as WORD16,
        ],
        dummy: 0 as WORD32,
        start_band: [
            [
                1 as core::ffi::c_int,
                2 as core::ffi::c_int,
                3 as core::ffi::c_int,
                4 as core::ffi::c_int,
                5 as core::ffi::c_int,
                6 as core::ffi::c_int,
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                9 as core::ffi::c_int,
                10 as core::ffi::c_int,
                12 as core::ffi::c_int,
                14 as core::ffi::c_int,
                16 as core::ffi::c_int,
                19 as core::ffi::c_int,
                23 as core::ffi::c_int,
                27 as core::ffi::c_int,
            ],
            [
                2 as core::ffi::c_int,
                3 as core::ffi::c_int,
                4 as core::ffi::c_int,
                5 as core::ffi::c_int,
                6 as core::ffi::c_int,
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                9 as core::ffi::c_int,
                10 as core::ffi::c_int,
                11 as core::ffi::c_int,
                13 as core::ffi::c_int,
                15 as core::ffi::c_int,
                17 as core::ffi::c_int,
                20 as core::ffi::c_int,
                24 as core::ffi::c_int,
                28 as core::ffi::c_int,
            ],
            [
                1 as core::ffi::c_int,
                3 as core::ffi::c_int,
                4 as core::ffi::c_int,
                5 as core::ffi::c_int,
                6 as core::ffi::c_int,
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                9 as core::ffi::c_int,
                10 as core::ffi::c_int,
                11 as core::ffi::c_int,
                12 as core::ffi::c_int,
                14 as core::ffi::c_int,
                16 as core::ffi::c_int,
                18 as core::ffi::c_int,
                21 as core::ffi::c_int,
                25 as core::ffi::c_int,
            ],
            [
                1 as core::ffi::c_int,
                3 as core::ffi::c_int,
                4 as core::ffi::c_int,
                5 as core::ffi::c_int,
                6 as core::ffi::c_int,
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                9 as core::ffi::c_int,
                10 as core::ffi::c_int,
                11 as core::ffi::c_int,
                12 as core::ffi::c_int,
                14 as core::ffi::c_int,
                16 as core::ffi::c_int,
                18 as core::ffi::c_int,
                21 as core::ffi::c_int,
                25 as core::ffi::c_int,
            ],
            [
                2 as core::ffi::c_int,
                4 as core::ffi::c_int,
                5 as core::ffi::c_int,
                6 as core::ffi::c_int,
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                9 as core::ffi::c_int,
                10 as core::ffi::c_int,
                11 as core::ffi::c_int,
                12 as core::ffi::c_int,
                13 as core::ffi::c_int,
                15 as core::ffi::c_int,
                17 as core::ffi::c_int,
                19 as core::ffi::c_int,
                22 as core::ffi::c_int,
                26 as core::ffi::c_int,
            ],
            [
                5 as core::ffi::c_int,
                6 as core::ffi::c_int,
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                9 as core::ffi::c_int,
                10 as core::ffi::c_int,
                11 as core::ffi::c_int,
                12 as core::ffi::c_int,
                13 as core::ffi::c_int,
                14 as core::ffi::c_int,
                15 as core::ffi::c_int,
                17 as core::ffi::c_int,
                19 as core::ffi::c_int,
                21 as core::ffi::c_int,
                23 as core::ffi::c_int,
                25 as core::ffi::c_int,
            ],
            [
                2 as core::ffi::c_int,
                4 as core::ffi::c_int,
                6 as core::ffi::c_int,
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                9 as core::ffi::c_int,
                10 as core::ffi::c_int,
                11 as core::ffi::c_int,
                12 as core::ffi::c_int,
                13 as core::ffi::c_int,
                14 as core::ffi::c_int,
                15 as core::ffi::c_int,
                17 as core::ffi::c_int,
                19 as core::ffi::c_int,
                21 as core::ffi::c_int,
                24 as core::ffi::c_int,
            ],
            [
                3 as core::ffi::c_int,
                5 as core::ffi::c_int,
                6 as core::ffi::c_int,
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                9 as core::ffi::c_int,
                10 as core::ffi::c_int,
                11 as core::ffi::c_int,
                12 as core::ffi::c_int,
                13 as core::ffi::c_int,
                14 as core::ffi::c_int,
                15 as core::ffi::c_int,
                17 as core::ffi::c_int,
                19 as core::ffi::c_int,
                21 as core::ffi::c_int,
                24 as core::ffi::c_int,
            ],
            [
                4 as core::ffi::c_int,
                5 as core::ffi::c_int,
                6 as core::ffi::c_int,
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                9 as core::ffi::c_int,
                10 as core::ffi::c_int,
                11 as core::ffi::c_int,
                12 as core::ffi::c_int,
                13 as core::ffi::c_int,
                14 as core::ffi::c_int,
                15 as core::ffi::c_int,
                16 as core::ffi::c_int,
                18 as core::ffi::c_int,
                20 as core::ffi::c_int,
                22 as core::ffi::c_int,
            ],
            [
                4 as core::ffi::c_int,
                5 as core::ffi::c_int,
                6 as core::ffi::c_int,
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                9 as core::ffi::c_int,
                10 as core::ffi::c_int,
                11 as core::ffi::c_int,
                12 as core::ffi::c_int,
                13 as core::ffi::c_int,
                14 as core::ffi::c_int,
                15 as core::ffi::c_int,
                16 as core::ffi::c_int,
                17 as core::ffi::c_int,
                18 as core::ffi::c_int,
                19 as core::ffi::c_int,
            ],
        ],
        stop_band: [
            [
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                10 as core::ffi::c_int,
                12 as core::ffi::c_int,
                14 as core::ffi::c_int,
                16 as core::ffi::c_int,
                19 as core::ffi::c_int,
                23 as core::ffi::c_int,
                27 as core::ffi::c_int,
                32 as core::ffi::c_int,
                38 as core::ffi::c_int,
                46 as core::ffi::c_int,
                54 as core::ffi::c_int,
                64 as core::ffi::c_int,
                78 as core::ffi::c_int,
                86 as core::ffi::c_int,
            ],
            [
                7 as core::ffi::c_int,
                8 as core::ffi::c_int,
                10 as core::ffi::c_int,
                12 as core::ffi::c_int,
                14 as core::ffi::c_int,
                16 as core::ffi::c_int,
                19 as core::ffi::c_int,
                23 as core::ffi::c_int,
                27 as core::ffi::c_int,
                32 as core::ffi::c_int,
                38 as core::ffi::c_int,
                46 as core::ffi::c_int,
                54 as core::ffi::c_int,
                64 as core::ffi::c_int,
                78 as core::ffi::c_int,
                86 as core::ffi::c_int,
            ],
            [
                10 as core::ffi::c_int,
                11 as core::ffi::c_int,
                13 as core::ffi::c_int,
                15 as core::ffi::c_int,
                17 as core::ffi::c_int,
                20 as core::ffi::c_int,
                23 as core::ffi::c_int,
                27 as core::ffi::c_int,
                31 as core::ffi::c_int,
                36 as core::ffi::c_int,
                42 as core::ffi::c_int,
                48 as core::ffi::c_int,
                55 as core::ffi::c_int,
                64 as core::ffi::c_int,
                78 as core::ffi::c_int,
                89 as core::ffi::c_int,
            ],
            [
                11 as core::ffi::c_int,
                12 as core::ffi::c_int,
                14 as core::ffi::c_int,
                16 as core::ffi::c_int,
                19 as core::ffi::c_int,
                22 as core::ffi::c_int,
                25 as core::ffi::c_int,
                28 as core::ffi::c_int,
                32 as core::ffi::c_int,
                37 as core::ffi::c_int,
                43 as core::ffi::c_int,
                49 as core::ffi::c_int,
                56 as core::ffi::c_int,
                64 as core::ffi::c_int,
                78 as core::ffi::c_int,
                90 as core::ffi::c_int,
            ],
            [
                12 as core::ffi::c_int,
                14 as core::ffi::c_int,
                16 as core::ffi::c_int,
                18 as core::ffi::c_int,
                20 as core::ffi::c_int,
                23 as core::ffi::c_int,
                26 as core::ffi::c_int,
                30 as core::ffi::c_int,
                34 as core::ffi::c_int,
                38 as core::ffi::c_int,
                43 as core::ffi::c_int,
                49 as core::ffi::c_int,
                56 as core::ffi::c_int,
                64 as core::ffi::c_int,
                78 as core::ffi::c_int,
                91 as core::ffi::c_int,
            ],
            [
                13 as core::ffi::c_int,
                15 as core::ffi::c_int,
                17 as core::ffi::c_int,
                19 as core::ffi::c_int,
                21 as core::ffi::c_int,
                24 as core::ffi::c_int,
                27 as core::ffi::c_int,
                31 as core::ffi::c_int,
                35 as core::ffi::c_int,
                39 as core::ffi::c_int,
                44 as core::ffi::c_int,
                50 as core::ffi::c_int,
                57 as core::ffi::c_int,
                64 as core::ffi::c_int,
                78 as core::ffi::c_int,
                92 as core::ffi::c_int,
            ],
            [
                16 as core::ffi::c_int,
                18 as core::ffi::c_int,
                20 as core::ffi::c_int,
                22 as core::ffi::c_int,
                24 as core::ffi::c_int,
                27 as core::ffi::c_int,
                30 as core::ffi::c_int,
                34 as core::ffi::c_int,
                38 as core::ffi::c_int,
                42 as core::ffi::c_int,
                46 as core::ffi::c_int,
                52 as core::ffi::c_int,
                58 as core::ffi::c_int,
                64 as core::ffi::c_int,
                78 as core::ffi::c_int,
                95 as core::ffi::c_int,
            ],
            [
                16 as core::ffi::c_int,
                18 as core::ffi::c_int,
                20 as core::ffi::c_int,
                22 as core::ffi::c_int,
                24 as core::ffi::c_int,
                27 as core::ffi::c_int,
                30 as core::ffi::c_int,
                34 as core::ffi::c_int,
                38 as core::ffi::c_int,
                42 as core::ffi::c_int,
                46 as core::ffi::c_int,
                52 as core::ffi::c_int,
                58 as core::ffi::c_int,
                64 as core::ffi::c_int,
                78 as core::ffi::c_int,
                95 as core::ffi::c_int,
            ],
            [
                17 as core::ffi::c_int,
                19 as core::ffi::c_int,
                21 as core::ffi::c_int,
                23 as core::ffi::c_int,
                25 as core::ffi::c_int,
                28 as core::ffi::c_int,
                31 as core::ffi::c_int,
                34 as core::ffi::c_int,
                38 as core::ffi::c_int,
                42 as core::ffi::c_int,
                47 as core::ffi::c_int,
                52 as core::ffi::c_int,
                58 as core::ffi::c_int,
                64 as core::ffi::c_int,
                78 as core::ffi::c_int,
                96 as core::ffi::c_int,
            ],
            [
                24 as core::ffi::c_int,
                26 as core::ffi::c_int,
                28 as core::ffi::c_int,
                30 as core::ffi::c_int,
                32 as core::ffi::c_int,
                35 as core::ffi::c_int,
                38 as core::ffi::c_int,
                41 as core::ffi::c_int,
                44 as core::ffi::c_int,
                47 as core::ffi::c_int,
                51 as core::ffi::c_int,
                55 as core::ffi::c_int,
                59 as core::ffi::c_int,
                64 as core::ffi::c_int,
                78 as core::ffi::c_int,
                10 as core::ffi::c_int,
            ],
        ],
        stop_freq_table_fs40k_2: [
            26 as core::ffi::c_int,
            28 as core::ffi::c_int,
            30 as core::ffi::c_int,
            32 as core::ffi::c_int,
            34 as core::ffi::c_int,
            36 as core::ffi::c_int,
            39 as core::ffi::c_int,
            42 as core::ffi::c_int,
            45 as core::ffi::c_int,
            48 as core::ffi::c_int,
            52 as core::ffi::c_int,
            56 as core::ffi::c_int,
            60 as core::ffi::c_int,
            0 as core::ffi::c_int,
        ],
        stop_freq_table_fs40k_4: [
            19 as core::ffi::c_int,
            21 as core::ffi::c_int,
            23 as core::ffi::c_int,
            25 as core::ffi::c_int,
            27 as core::ffi::c_int,
            30 as core::ffi::c_int,
            33 as core::ffi::c_int,
            36 as core::ffi::c_int,
            40 as core::ffi::c_int,
            44 as core::ffi::c_int,
            48 as core::ffi::c_int,
            53 as core::ffi::c_int,
            58 as core::ffi::c_int,
            0 as core::ffi::c_int,
        ],
    };
    init
};
